### ISSUE TITLE
Can't resolve 'perf_hooks' in linkedom at webworkers

### ISSUE THREAD

**Issue by guidiego** [WebReflection/linkedom#101]
Hello! I am trying to use `linkedom` as an alternative for `jsdom` at my webworker! Unfortunately, I am having an error related to perf_hooks during the build.

## Stack:
- Node 14.18
- CRACO: 6.4
- linkedom: 0.13

## Error
```
./src/features/webWorkerHub/index.worker.js
ModuleNotFoundError: Module not found: Error: Can't resolve 'perf_hooks' in '/Users/guidiego/workspace/.../node_modules/linkedom/esm/interface'
```

**Comment by WebReflection** [comment]
Are you importing `linkedom/worker` [as suggested in the readme](https://github.com/WebReflection/linkedom#whats-new)?

If not ... you should 😉

**Comment by WebReflection** [comment]
btw, I think 0.13.2 should stop showing errors around perf_hooks where this is not defined.
