### ISSUE TITLE
how to get the render then() delegate ?

### ISSUE THREAD

**Issue by timiil** [WebReflection/linkedom#102]
hi, for saying we had using the jsdom like this:
```
JSDOM.fromFile('index.html', options).then((dom) => {
  const window = dom.window;
  Object.defineProperty(window, 'localStorage', {
    value: localStorageMock
  });
  window.onload = ()=>{
    console.log("...",window.localStorage.getItem("htmlStr"));
  }
});
```

do we have the same thing in linkedom , about the render then event delegate, so we can add localStorage, can get something inside it.

many thanks :)

**Comment by WebReflection** [comment]
you can define `localStorage` if you like but `window.onload` has no meaning in *linkedom* ... [the window is there](https://github.com/WebReflection/linkedom#simulating-jsdom-bootstrap) for most SSR tasks, not to simulate a browser. If you want to simulate a browser keep using a project born to do that, which is JSDOM.

This project goal is **not** to simulate a browser, as stated [in this section of the README](https://github.com/WebReflection/linkedom#faq) (expand the first one).

**Comment by timiil** [comment]
ok. thanks for reply.  we are looking for simulation :)
