### ISSUE TITLE
MathJax and linkedom...

### ISSUE THREAD

**Issue by swamidass** [WebReflection/linkedom#105]
Has anyone figured out how to use MathJax on a linkedom object?

There are some tools for applying it to a jsdom (e.g. https://github.com/pkra/mathjax-node-page/), but I'd prefer to use linkedom.

**Comment by pkra** [comment]
FYI https://github.com/mathjax/MathJax-src/pull/774 exists now. It might not be what the OP was looking for but it shows that MathJax needs the same workarounds it needs for jsdom - not really unexpected but also not any more complex.

Side comment: I use linkedom for SSR with MathJax extensively but entirely without MathJax's document-level magic - I just run the "find equations" logic within linkedom and then run MathJax with its lite adaptor to render individual expression. 

I find this makes it much easier to control the resulting output.

**Comment by WebReflection** [comment]
@pkra awesome, thank you! It looks like there's not much to do in here then, at least until that MR lands. Closing for the time being.

**Comment by swamidass** [comment]
It looks like this is what's needed here, though I haven't tested it.

https://github.com/mathjax/MathJax/issues/2833#issuecomment-1032795953

I'll let you know if MathJax needs any unimplemented functionality.
