### ISSUE TITLE
Cannot read properties of undefined (reading 'clickfalse')

### ISSUE THREAD

**Issue by markwylde** [WebReflection/linkedom#109]
I'm having a problem with an app I'm building and have isolated it down to the following code snippet.

Basically, the steps to recreate are:
1. Create a new project
2. Init npm
3. Install `linkedom` and `preact`
4. Create an `index.js` file with the code below
5. Run `node index.js`
6. Receive the error `Cannot read properties of undefined (reading 'clickfalse')`

I can confirm the code works fine in Chrome. i.e. running `.click()` on the element.

## What is the code?
```javascript
import { parseHTML } from 'linkedom';
import { h, render } from 'preact';

function handleClick () {
  console.log('i gotted clicked')
}
const app = h('button', { onClick: handleClick }, 'Hello World!');

const {
  window, document
} = parseHTML(`
  <!doctype html>
  <html lang="en">
    <head>
      <title>Hello SSR</title>
    </head>
    <body>
    </body>
  </html>
`);

globalThis.document = document;
globalThis.window = window;

render(app, document.body);

const button = document.body.querySelector('button')
console.log(button.click())


```

## What is the error?
```
TypeError: Cannot read properties of undefined (reading 'clickfalse')
    at GlobalEvent.I (file:///home/mark/Synced/Projects/preact/node_modules/preact/dist/preact.mjs:1:4267)
    at GlobalEvent.dispatch (file:///home/mark/Synced/Projects/preact/node_modules/linkedom/esm/interface/event-target.js:7:14)
    at GlobalEvent.invokeListeners (file:///home/mark/Synced/Projects/preact/node_modules/linkedom/esm/interface/event-target.js:28:20)
    at Array.some (<anonymous>)
    at HTMLButtonElement.dispatchEvent (file:///home/mark/Synced/Projects/preact/node_modules/linkedom/esm/interface/event-target.js:80:17)
    at HTMLButtonElement.click (file:///home/mark/Synced/Projects/preact/node_modules/linkedom/esm/html/element.js:58:18)
    at file:///home/mark/Synced/Projects/preact/index.js:28:20
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
```

**Comment by WebReflection** [comment]
I am not sure what you are trying to do but LinkeDOM is **not** a replacement for a browser ... it's more about SSR. Clicking is not really about SSR though ... if you find a solution happy to read the MR but I won't work on this for the time being.

**Comment by markwylde** [comment]
I'm using it as a replacement for JSDOM for testing my preact user interface.

Could you point me in the direction of where to look at solving the above message? Is there a line you think that's causing it to throw?

Appreciate it's not a priority and thanks for all the work you've done on the project anyway.

**Comment by WebReflection** [comment]
this project goal is also *not* to replace JSDOM ... for browser-like things, JSDOM is the way to go.

If it's tests you are after, you are better off with JSDOM or real browsers (headless or not).

That being said, I have no idea, neither time, to check that error, sorry, and not a single file points at this project, it's all preact errors.

**Comment by markwylde** [comment]
Thanks @WebReflection for the help anyway. I've submitted a PR that fixes the issue I have, although if it breaks other things then I get you don't want to spend any time on it.

**Comment by WebReflection** [comment]
@markwylde I've fixed it slightly differently, improved readability for the future, and added a little test. This should be fine now, thanks for investigating 👋
