### ISSUE TITLE
Could you add release notes on whats new/breaking in each release?

### ISSUE THREAD

**Issue by Nashorn** [WebReflection/linkedom#115]
Could you add release notes on whats new/breaking in each release?

**Comment by WebReflection** [comment]
Breaking: nothing?
New: also nothing ... usually it's more about patching stuff, but yeah, I should definitively provide a better release flow, it just takes more time that I don't currently have, sorry.

Will keep this in mind next changes 👍

**Comment by Nashorn** [comment]
What i do when i make releases is add back my git comments as bullet points even if it's something like:

- Improved getDocument() to be more robust when handling null
- Fix to getFile() - releases mem lock..
and so on. 

:)

**Comment by WebReflection** [comment]
this page kinda shows those though ... I should be a bit more rigorous, I suppose ... anyway, not planning to release for patches, but I will do for minor/major changes
