### ISSUE TITLE
Why `getElementsByTagName` return a `NodeList` instead of a `HTMLCollection`

### ISSUE THREAD

**Issue by SettingDust** [WebReflection/linkedom#116]
Due to https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByTagName. The selecting methods beside `querySelector(All)` are return a `HTMLCollection`

**Comment by pkra** [comment]
From https://github.com/WebReflection/linkedom#faq 

> Are live collections supported?
> The TL;DR answer is no. Live collections are considered legacy, are slower, have side effects, and it's not intention of LinkeDOM to support these, [...]
