### ISSUE TITLE
Document.baseURI always undefined

### ISSUE THREAD

**Issue by SettingDust** [WebReflection/linkedom#117]
use `new DOMParser().parseFromString(html, 'text/html')` to parse for a `Document`. But the `baseURI` is `undefined` after I add a `base` element to head.

```
    const base = doc.createElement('base')
    base.href = inputUrl
    doc.head.appendChild(base)
```

**Comment by WebReflection** [comment]
not really an interesting case for SSR, isn't it?

**Comment by WebReflection** [comment]
Done. Not much logic needed/involved, it felt OK to make this happen ... it's a lazy thing, hope you're good now 👋

**Comment by SettingDust** [comment]
> Done. Not much logic needed/involved, it felt OK to make this happen ... it's a lazy thing, hope you're good now 👋

It's seems that there is somthing weird
![图片](https://user-images.githubusercontent.com/19922286/154668033-5e4d252c-7995-42a6-9310-a6a137c52988.png)
