### ISSUE TITLE
Add getComputedStyles

### ISSUE THREAD

**Issue by swamidass** [WebReflection/linkedom#118]
Seems like this should be possible by pulling this poly into linkedom:

https://github.com/mikemadest/jest-environment-linkedom/blob/main/src/get-computed-style-polyfill.js

This function is needed for several uses cases, including MathJax and Jest. Of course, those libraries can apply the polyfill, but it would be better for it to be added to linkedom to reduce barrier to use in this case and others.

**Comment by WebReflection** [comment]
I don't know what's that function for, neither I understand internals such as `this.el` nor what it's supposed to solve ... we recently did some change to this part but I am not planning to copy paste random pieces of 3rd party code into this project so I am afraid if you need anything better you need to explain the issue and what you expect as solution.

Once again, as mentioned all over this place, it's not a goal of this library to be 100% DOM compliant or yet another project for testing ... this module goal is to SSR or Worker rendering, not a replacement for JSDOM.

**Comment by swamidass** [comment]
I see this is probably far more difficult to implement than I thought.
