### ISSUE TITLE
markup-dependent crash with querySelector

### ISSUE THREAD

**Issue by pkra** [WebReflection/linkedom#120]
I realize it might be an issue in css-select but since it is markup dependent I thought I'd start here. 

Minimal example:

```js
import { DOMParser } from 'linkedom';
const doc1 = (new DOMParser).parseFromString('<span class="foo-1"/>', 'text/html').defaultView.window.document;
doc1.querySelector('[class*="foo-"]'); // the span
const doc2 = (new DOMParser).parseFromString('<svg class="foo-1"/>', 'text/html').defaultView.window.document;
doc2.querySelector('[class*="foo-"]'); // crash
```

**Comment by WebReflection** [comment]
does this happen only with a single root element or the same crash happens when such element is inside a div, as example?

I suspect for single svg element you want text/xml target goal instead

**Comment by pkra** [comment]
> does this happen only with a single root element or the same crash happens when such element is inside a div, as example?

Both. This was a _much_ reduced case from a complex document :wink:, trying to narrow it all the way down; the selector was actually trying to match paragraphs but the inline svgs tripped things up. In any case, I could easily work around it.)

**Comment by WebReflection** [comment]
how would you work around this?

**Comment by pkra** [comment]
> how would you work around this?

I only meant that in my specific situation I could switch from `[class*="foo-"]` to `p[class*="foo-"]`.

**Comment by WebReflection** [comment]
this module does not implement any selector engine, it uses a 3rd party module for that ... I might have a look when I find the time to do so ... if you find any clue where the selector engine fails please let me know, thanks.

**Comment by pkra** [comment]
> this module does not implement any selector engine, it uses a 3rd party module for that 

Right, I realize this could be a css-select bug but didn't have time to go deeper. 
What struck me as strange was that it only seems to crash if there's an svg element in the document.

**Comment by WebReflection** [comment]
svg changes the parsing goal, and because this is empty, maybe there is an issue there ... does this happens with non empty svg too?

**Comment by pkra** [comment]
> svg changes the parsing goal, and because this is empty, maybe there is an issue there ... does this happens with non empty svg too?

Yes.

I made a tiny bit of progress digging into css-select's `attribute.js`. There, `adapter.getAttributeValue` returns `{ baseVal: '', animVal: '' }` for the svg but `foo-1` for the span. 

This seems to point to 

https://github.com/WebReflection/linkedom/blob/5317bffb37b914cecb9a31d5a9179eae7f8ffcc0/esm/svg/element.js#L24-L27

**Comment by pkra** [comment]
(Replacing this with  `get className() { return this.classList.value; }` seems to fix things but I'm guessing there's a reason for the complications.)

**Comment by WebReflection** [comment]
try this in an empty document and an opened console:

```js
document.body.innerHTML = '<svg></svg>';
document.body.firstChild.className;
```

there you go, you have something else from the SVG world, and linkedom just replicates it.

Accordingly, what I think should be done, is to check SVG in the adapter and return the `this.classList.value` instead for that case.

**Comment by pkra** [comment]
> there you go, you have something else from the SVG world, and linkedom just replicates it.

Ouch. That's horrific. Thank you for taking another look!
