### ISSUE TITLE
linkedom/worker.js

### ISSUE THREAD

**Issue by kostia-lev** [WebReflection/linkedom#122]
It is not an issue of worker.js, but probably people will find it userful.
I have error when I run test suite:
    SyntaxError: Unexpected token 'export'

    > 12 | import {parseHTML} from "linkedom/worker";

Can anyone please help with configuring jest to transpile correctly?

**Comment by WebReflection** [comment]
I don’t care about 3rd party issues, sorry, and if you go, this is the wrong repository so it won’t get fixed in here.
