### ISSUE TITLE
Cannot set property eventPhase of #<Event> which has only a getter

### ISSUE THREAD

**Issue by thepassle** [WebReflection/linkedom#130]
Hey there, I'm trying to use this package to SSR some vanilla custom elements. One of my components uses a Mixin, in which I call 

```js
      this.dispatchEvent(
        new CustomEvent('selected-changed', {
          detail: selected,
        }),
      );
```
(you can see the code here: https://github.com/thepassle/generic-components/blob/master/utils/SelectedMixin.js#L69-L73)

However, running that code gives me the following error:
```
/Users/au87xu/genc/node_modules/linkedom/cjs/interface/event-target.js:73
    event.eventPhase = event.CAPTURING_PHASE;
                     ^

TypeError: Cannot set property eventPhase of #<Event> which has only a getter
    at GenericTabs.dispatchEvent (/Users/au87xu/genc/node_modules/linkedom/cjs/interface/event-target.js:73:22)
    at GenericTabs.__dispatch (file:///Users/au87xu/genc/node_modules/@generic-components/components/utils/SelectedMixin.js:69:12)
    at GenericTabs.requestUpdate (file:///Users/au87xu/genc/node_modules/@generic-components/components/utils/BatchingElement.js:19:16)
```

If I comment out the contents of the `dispatchEvent` function in `interface/event-target.js` everything runs as expected

**Comment by WebReflection** [comment]
Can you do that in browsers?

**Comment by WebReflection** [comment]
And why would you?

**Comment by WebReflection** [comment]
To clarify, this project will s about SSR and anything that brings nothing but bloat won’t land in here, so I’m trying to understand what’s this bug about …

**Comment by thepassle** [comment]
Because its very common for custom elements to dispatch events. I understand that on the server its not really wanted, but it is the behavior of my component in the browser

**Comment by WebReflection** [comment]
It’s not common to change event phase though, so I do t understand what’s this bug about … can you please show a real world use case?

**Comment by thepassle** [comment]
Im not trying to change the event phase. My component onlh calls this.dispatchEvent with a new CustomEvent which leads to the error. Im not really doing anything exotic, just firing an event

**Comment by thepassle** [comment]
I've tried to create a minimal reproduction on stackblitz, but I cant seem to accomplish that... I did however find out this:

It seems that for some reason in `interface/custom-event.js`, the following ternary:
```js
 */
const GlobalCustomEvent = typeof CustomEvent === 'function' ?
  CustomEvent :
  class CustomEvent extends Event {
    constructor(type, eventInitDict = {}) {
      super(type, eventInitDict);
      this.detail = eventInitDict.detail;
    }
  };
```

`typeof CustomEvent === 'function' // true` 

If I remove that ternary, and just do:
```js
const GlobalCustomEvent =   class CustomEvent extends Event {
    constructor(type, eventInitDict = {}) {
      super(type, eventInitDict);
      this.detail = eventInitDict.detail;
    }
  };
```

Then everything works as expected. In which case would `typeof CustomEvent === 'function'` already? Any idea? 🤔

**Comment by thepassle** [comment]
Aha... I figured it out. Something on my server was already polyfilling CustomEvent, so the ternary would use the already-polyfilled CustomEvent and then not match. The issue was on my end 🙂
