### ISSUE TITLE
setAttribute/removeAttribute not clearing cache

### ISSUE THREAD

**Issue by aghull** [WebReflection/linkedom#134]
When using the cached version, attribute changes from adding or removing attributes do not reset the cache and allow stale cache results to show up. E.g. given a `node` with children:
```
assert(node.querySelector('[c]'), null);
node.childNodes[0].setAttribute('c', '3');
assert(node.querySelector('[c]'), node.childNodes[0]); // FAIL
```
The above fails with the cached empty result

```
node.childNodes[0].setAttribute('d', '4');
assert(node.querySelector('[d]'), node.childNodes[0]);
node.childNodes[0].removeAttribute('d');
assert(node.querySelector('[d]'), null); // FAIL
```
The above fails with the cached non-empty result

**Comment by WebReflection** [comment]
This indeed looks like a bug. Any particular reason you’re using the cached version, if I might ask?

**Comment by WebReflection** [comment]
Never mind, I've patched the issue for all missing methods too now.

**Comment by aghull** [comment]
I'm using it for a project that does a lot of XML querying and manipulation and wanted a really fast QSA. The caching would help me a lot and if I don't use this, I'd probably roll my own.
