### ISSUE TITLE
.innerText doesn't add \n newlines like browser does

### ISSUE THREAD

**Issue by devinellis** [WebReflection/linkedom#136]
Thanks for providing `linkedom/worker` export,  I'm using it within a Cloudflare WebWorker to separate navigation from content using Mozilla's Readability library. The last step is to get the innerText of the page content. If a page's HTML is minified, words in separate block elements get joined together:

### Steps to Reproduce
```
const {document} = parseHTML(`<html><body><div>The <strong>quick</strong> brown fox</div><div>Jumped over<br>The lazy dog</div></body></html>`)

document.body.innerText
```

**Returns**
```The quick brown foxJumped overThe lazy dog```

**Expected (Firefox and Chrome)**
```The quick brown fox\nJumped over\nThe lazy dog```

I verified this behavior in Chrome and Firefox. As far as I can tell, they do it for block level elements, `<br>`, and maybe others.

This is causing things like `<li>` lists to get merged together. My temporary fix is to append a whitespace to every text node, but this is causing issues like runon sentences.

I know converting to plaintext isn't a main use-case for your library. As you can imagine, these edge workers are very resource limited and JSDOM won't run there at all.

Thanks

**Comment by WebReflection** [comment]
I don’t understand the use case at all and I won’t work on this, but PR welcome (and tests) and also a use case maybe ….

**Comment by devinellis** [comment]
I can see about making a PR. The use-case isn't SSR (as you've stated is the main goal of the project) it's basically web scraping, but on an edge worker with limited resources, making JSDOM a no-go.

**Comment by devinellis** [comment]
Ok I threw together a PR. But in the end, I think what's probably best is for me to just build what I need using your TreeWalker implementation, and skip using innerText.

So feel free to close out if you prefer.

**Comment by WebReflection** [comment]
I like the PR, and it’s all green … I’ll recheck tomorrow and push it live if everything is fine, thank you 👋

**Comment by WebReflection** [comment]
it's in after minor adjustments, thanks again.
