### ISSUE TITLE
Define same custom elements across multiple documents

### ISSUE THREAD

**Issue by CaptainJKoB** [WebReflection/linkedom#138]
Hello 👋 

In the sample on the bottom of the issue, a different document is created on each route and one custom element should be shared across them. If you access any route for the first time it's perfectly fine, the site renders but for the second time on any route linkedom throws:
```cmd
Uncaught Error: unable to redefine the same class: class CustomElement extends HTMLElement { ... }
```

After some digging in the code i found out that the class saved in the `Classes` WeakMap is coupled with the document it was defined on:
https://github.com/WebReflection/linkedom/blob/f087291c5f53496053319feb9ddc1b9fe2b8d3a4/esm/interface/custom-element-registry.js#L104-L117
Which makes elements globally coupled only with one document.

I thought it may be possible to tie the class to its customElements ownerDocument, but there is the catch in `HTMLElement` which, if `ownerLess` then gets the class  from `Classes` and uses it's `ownerDocument`. And i am not really sure how to approach it from there. 🤔 
https://github.com/WebReflection/linkedom/blob/f087291c5f53496053319feb9ddc1b9fe2b8d3a4/esm/html/element.js#L35-L43

Would it be possible to define same custom elements across multiple documents?
Or is there a better approach for creating multiple dynamic documents sharing custom elements?
Haven't really found an answer, so any help or direction is appreciated. 

Thank you :+1:

Node: v16.14.2
linkedom: 0.14.9

```js
const { parseHTML, HTMLElement } = require('linkedom');
const { createServer } = require('http');


class TestElement extends HTMLElement {

  connectedCallback() {
    this.innerHTML = 'Hello world!';
  }

}

createServer((req, rep) => {
  let document, customElements;
  if (req.url === '/document') {
    const parsed  = parseHTML('<!DOCTYPE html><html><head><title>Document</title><body><test-element></test-element></body></html>')
    document = parsed.document;
    customElements = parsed.customElements;
  } else {
    const parsed = parseHTML('<!DOCTYPE html><html><head><title>Index</title><body><test-element></test-element></body></html>');
    document = parsed.document;
    customElements = parsed.customElements;
  }
  customElements.define('test-element', TestElement);
  rep.statusCode = 200;
  rep.write(document.toString())
  rep.end();
}).listen(8888);
```

**Comment by Nashorn** [comment]
Not a linkedom issue. You cannot redefine a custom element more than once. Your call to 
customElements.define('test-element', TestElement); must be running multiple times.
You could try to see if it is already defined:

var ctor = customElements.get('test-element');
if(!ctor) {
    customElements.define('test-element', TestElement);
}

**Comment by WebReflection** [comment]
@CaptainJKoB sorry for the delay. So ... it's true that current dance is a bit of a shenanigan because of the *ownerLess* use case which, common or not, gotta be supported.

The current state is:

  * each `globalThis` or *window* gets its own registry
  * each registry is coupled with the document it represents; this is needed to support *ownerLess* Custom Elements
  * I can't ignore already registered classes per `document`, or override it, because you could cache multi documents per route and last updated upgrades them all in a breaking way

**The solution** is, for the time being, on your side: provide disambiguation across documents still ensuring no duplicated custom elements name can be used per document.

How would you do that? just like this:

```js
customElements.define('test-element', class extends TestElement {});
```

Done?

**Comment by WebReflection** [comment]
Closing this, as I don't think I'll work on anything more complicated than that which is, imho, a pretty lightweight and elegant solution. The `Classes` is a `WeakMap` too, so once the `document` gets de-referenced, Classes would be dropped as well.
