### ISSUE TITLE
svg `linearGradient` gets transformed to `lineargradient`

### ISSUE THREAD

**Issue by gingerchris** [WebReflection/linkedom#139]
Thanks again for this amazing project.

I've found that importing an SVG containing a `<linearGradient>` results in the gradient not rendering.  This is because the tag name is transformed to lowercase at some point, so `linearGradient` becomes `lineargradient` which is not compatible.

## Steps to reproduce (or [see here](https://stackblitz.com/edit/node-s4fxxu?file=index.js,package.json))
```js
import { parseHTML } from 'linkedom';

const input = `
  <svg viewBox="0 0 30 30" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" >
    <linearGradient id="gradient" x1="0" y1="0" y2="30" x2="0" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="black" />
      <stop offset="1" stop-color="red" />
    </linearGradient>
    <rect width="30" height="30" fill="url(#gradient)" />
  </svg>`;

const parsed = parseHTML(input);

console.log(parsed.document.toString());

```

Are all tag names transformed to lowercase?

I'm happy to work on a fix for this, but could you give me some pointers please so I know where to start?

Thanks

**Comment by WebReflection** [comment]
you are parsing XML there though, not HTML ... you want [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser/parseFromString) with the correct type.

if that was inside an HTML tag though, everything would be fine. Put a `<div>` around and see.

**Comment by WebReflection** [comment]
> Are all tag names transformed to lowercase?

HTML is case insensitive, while SVG / XML is case sensitive.

The SVG parser switches automatically when an SVG node is within HTML, if you pass an SVG right away though, that's like parsing XML.

If you can't fix by importing `DOMParser` instead and `const document = (new DOMParser).parseFromString('<root></root>', 'text/xml');` let me know.

**Comment by gingerchris** [comment]
@WebReflection I'm so sorry for wasting your time!  Thank you very much for answering and explaining - you're right that this change fixes it

**Comment by pkra** [comment]
Random side comment because it reminds me of some trouble I had a while back: better support for xhtml serialization would be great, e.g., for epub production. (I wish I could find the time to dig into it again but camel-cased attributes for inline SVG was definitely one problem.)

**Comment by WebReflection** [comment]
@pkra you can use XML parser for anything you want, including XHTML ... you don't need to use the HTML parser for non HTML, actually that's you chosing the wrong parser. I can't use a crystal ball to understand your intent, and this is SSR, not browser, so use the XML if camelCase and self closing tags matter, and call it a day? 🤔
