### ISSUE TITLE
`document.documentElement.outerHTML` only return the `head`

### ISSUE THREAD

**Issue by SettingDust** [WebReflection/linkedom#146]
The document seems isn't holding the first child

**Comment by WebReflection** [comment]
`document.toString()` does so I am not sure why you'd go that way ... can you just use `document.toString()` as that's how this module produces pages?

**Comment by SettingDust** [comment]
> `document.toString()` does so I am not sure why you'd go that way ... can you just use `document.toString()` as that's how this module produces pages?
> 
> _edit_ I might as well make that the default `documentElemnet.outerHTML` but I wodner why you can't use `document.toString()` in the first place ...

`toString` is ok. But
![](https://user-images.githubusercontent.com/19922286/176678132-c8401976-ae37-4020-b626-4c8373a0bc72.png)

**Comment by WebReflection** [comment]
@SettingDust is that a screenshot of devtools console? 'cause [here things are different](https://github.com/WebReflection/linkedom/blob/main/esm/interface/document.js#L255) and thqt's irrelevant

**Comment by WebReflection** [comment]
@SettingDust also bear in mind `documentElement.outerHTML` does not include the `!doctype` node declaration ... you need to use `document.toString()` with linkedom, you need something else on the browser that checks all `document.childNodes`

**Comment by SettingDust** [comment]
> @SettingDust is that a screenshot of devtools console? 'cause [here things are different](https://github.com/WebReflection/linkedom/blob/main/esm/interface/document.js?rgh-link-date=2022-07-01T06%3A09%3A00Z#L255) and that's irrelevant

That's why I don't use `toString`

**Comment by WebReflection** [comment]
I don't understand what you are after ... this module has nothing to do with Firefox or Chrome or Safari, is that clear? If you use this module to server render pages you need to use `document.toString()`.

**Comment by SettingDust** [comment]
But `document.documentElement.outerHTML` shouldn't only return the head

**Comment by WebReflection** [comment]
@SettingDust this issue is misleading and it provides zero code to reproduce anything you are after ... this is not how issues work here ... you need to provide a valid title, a minimal use case to test, write expectations, and then there's something for me to look at ... here I have nothing: a title and links to Firefox toString() or a screenshot of devtools that has nothing to do with linkedom and so on ... feel free to open a new issue following these instructions, I am locking this one now.
