### ISSUE TITLE
why it is not allowed to redefine a custom element

### ISSUE THREAD

**Issue by pYr0x** [WebReflection/linkedom#148]
i wondering why it is not allowed to redefine a custom element https://github.com/WebReflection/linkedom/blob/main/cjs/interface/custom-element-registry.js#L108-L109

if you have something like a HMR you need to redefine the custom element to see the changes.

**Comment by WebReflection** [comment]
least surprise ... it encourage using multiple documents if different Custom Elements with same name are needed.

HMR requires the registry itself to be reloaded so there should be no issue whatsoever.

**Comment by WebReflection** [comment]
P.S. this is also standard Custom Elements Registyr behavior.

**Comment by pYr0x** [comment]
i don't know why you said linkedom is not too close to the standard, but here you insist exactly on the standard... but ok. 

_HMR requires the registry itself to be reloaded so there should be no issue whatsoever._
i do not see any solution in your answer

**Comment by WebReflection** [comment]
HMR requires you invalidate previously loaded modules ... that includes the registry, right? I also don't accept any tone that is beyond respectful so you've been warned.

**Comment by WebReflection** [comment]
https://github.com/WebReflection/linkedom/blob/main/how-to-contribute.md
