### ISSUE TITLE
Linkedom recognizes only the first element if the elements are not wrapped with a container

### ISSUE THREAD

**Issue by RafidMuhymin** [WebReflection/linkedom#152]
I am enjoying `linkedom` so far, it's fast and easy to use. But I hit an issue today. If the elements of a document are not wrapped with a parent element, such as `html`, `linkedom` recognizes only the first element.

Code Example:

```js
import { parseHTML } from "linkedom";

const { document } = await parseHTML(
  `<div>I am a div</div><div>I am another div</div>`
);

console.log(document.documentElement.outerHTML); /* <div>I am a div</div> */
```

**Comment by WebReflection** [comment]
I don't have a use case for that ... how about you create a document fragment, or any other container, and use its `innerHTML` instead? You are accessing a `document.codumentElement` that's never going to be a document fragment so I am not sure why we should change that.

As there are workarounds and neither the use case nor its expectations are clear, I am going to close this but feel free to ask more if needed.

**Comment by RafidMuhymin** [comment]
Thanks for your response @WebReflection ! You are definitely correct. But I thought it's an issue because `linkedom` is not even recognizing the rest of the elements. Though `linkedom` doesn't try to be compliant with the specs, I thought it at least follows the rule/convention that *For any non-empty HTML document, documentElement will always be an `<html>` element.* I didn't found any mention of this that the elements must be wrapped within a fragment or container in the readme or somewhere else.

**Comment by WebReflection** [comment]
to create fragments you have document fragment or the `template` element ... latter one allows you to do whatever you want and, if it doesn't, I'd rather fix that. 

The reason LinkeDOM is fast is that it doesn't care about broken use cases and this, I am afraid, has all the right checks to look like one, so I won't work on that, as it's not clear what you want or why ... sloppyness ends up creating slow monsters full of code branches and here I believe nobody wants those things, would you agree?

**Comment by RafidMuhymin** [comment]
Thank you for your response again @WebReflection ! I have found what I was looking for, `document.toString()`. It does exactly what I want. Of course, I agree with you. I was trying to use `document.doucmentElement.outerHTML` to replace the previous HTML code with the new manipulated HTML, which did not match with the structure with the original code in too many cases. But `document.toString()` does exactly what I want, even the position of the strings are unchanged. Nice work, Andrea. Thank you so much for this awesome library.
