### ISSUE TITLE
Missing `splitText` on `Text` node

### ISSUE THREAD

**Issue by aloisdeniel** [WebReflection/linkedom#156]
Hello!

Thanks for this amazing package!

I just miss the [Text.splitText](https://developer.mozilla.org/en-US/docs/Web/API/Text/splitText) method.

In the meantime, I'm using this naive implementation :

```js
dom.Text.prototype.splitText = function (offset) {
  const [start, end] = (() => {
    if (offset <= 0) return ['', this.data];
    if (offset >= this.data.length) return [this.data, ''];
    return [
      this.data.substring(0, offset),
      this.data.substring(offset),
    ];
  })();

  const newNode = dom.document.createTextNode(end);
  this.parentNode.insertBefore(newNode, this.nextSibling);
  this.data = start;
  return newNode;
};
```

Thanks.

**Comment by WebReflection** [comment]
why not filing a PR instead? I don't mind naive implementations as long as not obtrusive for the fast-path use case and working reasonably well (and code-covered, of course).

**Comment by WebReflection** [comment]
not enough interest in this, closing until PR available.
