### ISSUE TITLE
Missing `window.Location` (the constructor)

### ISSUE THREAD

**Issue by fregante** [WebReflection/linkedom#159]
Due to some TypeScript code that uses `instanceof Location` to tell an argument apart from other types of URLs, I'd need this global class. I was unable to locate where exactly the `location` property is generated in this codebase.

**Comment by WebReflection** [comment]
there's no location here ... it's SSR: you define the location? add a global class would be my answer but that might not solve, right?

**Comment by fregante** [comment]
This is not a location?

```js
const {window} = parseHTML('')
window.location
```

I'm just asking  `window.location` to be an instance of `window.Location`, which currently doesn't exist in the first place. 

I already know what a workaround would be, I'm suggesting to add a class so that I don't need to work around this.

If it doesn't belong to linkedom because you want to keep it light, that's fair.

**Comment by WebReflection** [comment]
If location is exposed (can’t remember, sorry) then it’s ok to expose Location class.

mind filing a PR?

**Comment by WebReflection** [comment]
actually ... [tests show that location](https://github.com/WebReflection/linkedom/blob/main/test/html/document.js#L72-L75) is something you pass along, so you can add Location globally, or should I check if location is available (passed) and return its proto constructor?

**Comment by WebReflection** [comment]
Closing as no interest shown whatsoever for more than a month.
