### ISSUE TITLE
Expose the Text constructor

### ISSUE THREAD

**Issue by jeswin** [WebReflection/linkedom#16]
In addition to checking node.nodeType, another way to check if a node is a Text node is:

```js
const isTextNode = node instanceof Text;
```

But currently parseHTML() does not return the Text constructor, though it returns window, document, HTMLElement etc. This of course isn't specific to Text; for compatibility we might need all the other globals as well.

Would it be better to attach them to window, which is returned from parseHTML() anyway?

**Comment by WebReflection** [comment]
I might expose that, but the issue is that internal classes cannot ne initialized via `new Text`, as example, while checking `nodeType` is the cheapest/fastest operation ever here, as it's a direct property.

**Comment by jeswin** [comment]
Ah I see. Text is in the spec, but I can see why you might wanna keep it out (like you might want to avoid implementing everything, and becoming bloated). 

What might make the decision harder is that the instanceof check is needed in some other similar cases - for example differentiating HTMLElement from SVGElement. So would we expose SVGElement but not Text?

What's the vision for linkedom? Is it to become a lighter, faster alternative to JSDOM?

**Comment by WebReflection** [comment]
`HTMLElement`, as well as every other *HTML* class, is necessary to create *Custom Elements* and it doesn't require special parameters to be extended, it's an empty constructor, everything else is specialized and cannot be extended with the same ease.

*SVGElement* cannot be used to create *Custom Eements*, so it's not exposed.

To check if an element is *SVG* though, you need to check `'ownerSVGElement' in node` ... and `instanceof` has never been a great check in general, plus it's slower than `nodeType` or `'ownerSVGElement' in node` so I am not sure I should bother with exporting everything, as that creates another problem: people incapable of extending stuff ...

**Comment by WebReflection** [comment]
P.S. nothing really stops you to trap constructors though, if you really are after `instanceof` checks.

```js
const Text = document.createTextNode('').constructor;
```

**Comment by jeswin** [comment]
Thanks for the pointers. createTextNode().constructor is how I've been handling it.

I agree with your points, so I'll just go ahead and close this.

Thanks.

**Comment by WebReflection** [comment]
You know what? I can keep the classes internally and exposes, trough the `document.defaultView` classes you can use, or extend, as you like, inferring the current running document automatically.

would that work? These will be different per each document, so I’m not sure that’d be more, or less, confusing, but the ownerDocument is the root of everything here

**Comment by WebReflection** [comment]
Well, that makes things easier for both of us, as you have a Text class shared across documents, so instanceof won’t fail ... but I’m sure more similar requests will land, hence I’ll try to see if I can provide HTMLElement like solution, for all classes.

**Comment by jeswin** [comment]
That'll work for me, thanks. But do this only if it aligns with your vision, I certainly don't want to cause any unnecessary bloat with my corner cases.

**Comment by WebReflection** [comment]
@jeswin actually I can export facades that cannot be extended or initialized, preserving real DOM behavior when you cannot really do `new Text`, and this could work for every single exported constructor, except those meant to be initialized, or extended, like `HTML*`, `DOMParser`, etc ... this should work and satisfy all needs, without going too weird with classes per document.
