### ISSUE TITLE
Always return full document (html, head, body) even with empty html strings, like browsers do

### ISSUE THREAD

**Issue by fregante** [WebReflection/linkedom#160]
### Chrome

<img width="487" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/189404155-fdc3d359-c2ca-49de-ae7d-8890fd3b44e8.png">

### Linkedom

<img width="526" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/189404229-59747f7d-f86e-4f37-91f0-f556913222d4.png">

**Comment by WebReflection** [comment]
why don't you fallback when you have nothing to parse? this issue keeps coming up and I am not sure it's me or people too sloppy around this project ...

**Comment by fregante** [comment]
I don't understand your tone. This is not about "sloppiness" but about matching what others are doing. 

Most of the time I just need to get a `document` to work on and I don't care about its content. The least amount of code this requires, the better.

**Comment by WebReflection** [comment]
It’s not a tone, rather a genuine question. People just wanting a document can use new Document instead, or maybe they don’t want head and body? 

I just think once i fallback somebody might ask why there is a doctype, a head, and a body.

No need to close PRs while trying to understand use cases.

**Comment by WebReflection** [comment]
P.S. I didn’t mean to have “a tone” … this issue keeps coming up so devs either don’t search for previous conversations or really want to raise this again hoping for a different outcome. If passing entry strings is so common let’s fallback on a minimal document. Mind filing a PR?

**Comment by WebReflection** [comment]
you can now use '...' to signal you want a whole new document with head and body

**Comment by WebReflection** [comment]
then parse with a `'...'` fallback if the site returns no content?
