### ISSUE TITLE
MediaSource/HTMLMediaElement support?

### ISSUE THREAD

**Issue by yegor211** [WebReflection/linkedom#165]
Hi. I didn't find it anywhere yet (maybe I missed something) but does linkedom provide support for MediaSource and other stuff related to media?

This is quite crucial for the current app I'm working on (which has to have that support in the Service Worker).

If anyone can also point me to any possible options (if linkedom doesn't have support or ability to get extended) - I would be happy to hear.

Thanks.

**Comment by WebReflection** [comment]
what kind of support are you considering? about contributing, [the folder with elements with special features is here](https://github.com/WebReflection/linkedom/tree/main/esm/html) and [how to contribute here](https://github.com/WebReflection/linkedom/blob/main/how-to-contribute.md).

**Comment by yegor211** [comment]
> what kind of support are you considering? about contributing, [the folder with elements with special features is here](https://github.com/WebReflection/linkedom/tree/main/esm/html) and [how to contribute here](https://github.com/WebReflection/linkedom/blob/main/how-to-contribute.md).

Thanks. I need to be able to use `MediaSource` as in normal environment (eg `new MediaSource()` etc).

Is it possible?

**Comment by yegor211** [comment]
Sorry, closed by accident, not closed yet!

**Comment by WebReflection** [comment]
> I need to be able to use MediaSource as in normal environment (eg new MediaSource() etc).

it is possible, the missing bits might be around accessors you'd like to set or get, and that's where things might become less granted/trivial ... hence my link to the (not even fully) supported elements. Is your element there? Great! Feel free to add anything it's missing in terms of accessors ... is it not? Apologies, for the purpose of the SSR library that might be missing or not too interesting, hence feelfree to file a PR there 👍
