### ISSUE TITLE
Input value is null

### ISSUE THREAD

**Issue by emmby** [WebReflection/linkedom#166]
First time user, hit an unexpected behavior when trying to access the value of input elements. Other attributes like `id` are just fine, but `value` does not seem to be present in the parsed output.

```
// typescript
var input = <HTMLInputElement>parseHTML("<input id='foo' value='bar'/>").document.children[0];
console.log(input.id);       // foo
console.log(input.value);    // undefined
```

Is this expected behavior?

**Comment by WebReflection** [comment]
It's up 👋

**Comment by emmby** [comment]
works great, thanks for the very quick turnaround!

**Comment by WebReflection** [comment]
> 

Thank you for the report 👍
