### ISSUE TITLE
Webpack build issues

### ISSUE THREAD

**Issue by DarrenCook** [WebReflection/linkedom#169]
I get the below error when using webpack. 

``` 
error  in ./node_modules/htmlparser2/lib/esm/index.js

Module parse failed: Unexpected token (59:9)
File was processed with these loaders:
 * ./node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js
You may need an additional loader to handle the result of these loaders.
|     return getFeed(parseDOM(feed, options));
| }
> export * as DomUtils from "domutils";
| // Old name for DomHandler
| export { DomHandler as DefaultHandler };

 @ ./node_modules/linkedom/esm/shared/parse-from-string.js 1:0-43 10:17-28
 @ ./node_modules/linkedom/esm/dom/parser.js
 @ ./node_modules/linkedom/esm/index.js
 @ [our source file]
 ```
 
 **Additional Information:**
 
 I added `const { DOMParser } = require('linkedom')` to the top of a file, hoping it would work as a drop-in replacement. The code then does:
 
 ```
const parser = new DOMParser()
const xmlDoc = parser.parseFromString(xmlStr, 'text/xml')
...
```

The only other webpack-related issue I saw was #140.

The build process is actually Quasar, V1, which is using WebPack 4, I think.

I get similar webpack `Unexpected token` errors when trying to use jsdom@20.0.0  (which is why I've been trying alternative libraries).

**Comment by WebReflection** [comment]
no matter how many alternatives you try if the bug comes from a dependency https://github.com/fb55/htmlparser2
