### ISSUE TITLE
template elements have an empty innerHTML

### ISSUE THREAD

**Issue by MathGeniusJodie** [WebReflection/linkedom#17]
it looks like template elements have an innerHTML of an empty string

**Comment by MathGeniusJodie** [comment]
`template.content.toString()` also gives an empty string, but `template.toString() shows the content just fine

**Comment by MathGeniusJodie** [comment]
replaceChildren looks like the issue, but a quick glance of the source code reveals no obvious mistakes

**Comment by MathGeniusJodie** [comment]
my temporary fix was to rewrite the getter on template elements
  ```js
  get innerHTML() {
    const {unescape} = require('html-escaper');
    return unescape(this.childNodes.join(''));
    //return this.content.toString();
  }```

**Comment by WebReflection** [comment]
you set `template.innerHTML` and you use the `template.content`, which is what has been tested.

what doesn't work, exactly?

**Comment by MathGeniusJodie** [comment]
I figured it was too simple to require a reduced test case, but here you go
```js
const { parseHTML } = require("linkedom");
const test = parseHTML("<template><div>foo</div><div>bar</div></template>");
const template = test.document.querySelector("template");
console.log(template.content.toString()); // empty string
console.log(template.innerHTML); // empty string
```

**Comment by WebReflection** [comment]
> I figured it was too simple to require a reduced test case, but here you go

it's never the case, as there might be some obvious thing you are doing it wrong, but it takes nothing for me to reproduce the issue you are having so, thanks for the example, I'll have a look, although I'm after much bigger refactoring so this might help me covering such refactoring.

**Comment by MathGeniusJodie** [comment]
this is a very ambitious project you're taking on

**Comment by WebReflection** [comment]
btw, I can confirm the bug and it will be solved with the next release/minor update

**Comment by WebReflection** [comment]
@MathGeniusJodie please give latest a try and let me know if you find other issues, thanks 👋

**Comment by MathGeniusJodie** [comment]
I've got a pretty big ssr project I'm working on, I'll find bugs fast
