### ISSUE TITLE
Select `<option>` `value` field is `undefined`

### ISSUE THREAD

**Issue by MadLittleMods** [WebReflection/linkedom#170]
Similar to https://github.com/WebReflection/linkedom/issues/166

The `value` field is `undefined` for [`<option>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option) elements.

```js
parseHTML(`<select><option id="foo" value="foo">foo</option></select>`).document.querySelector('option').id;
// 'foo'

parseHTML(`<select><option id="foo" value="foo">foo</option></select>`).document.querySelector('option').value;
// undefined

parseHTML(`<select><option id="foo" value="foo">foo</option></select>`).document.querySelector('option').getAttribute('value');
'foo'
```

---

It would be nice if you could get the `value` from a [`<select>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) element as well but I understand this may be a bit less straight-forward.

```js
parseHTML(`<select id="form-select"><option value="foo" selected="selected">foo</option></select>`).document.querySelector('select').id;
// 'form-select'

parseHTML(`<select id="form-select"><option value="foo" selected="selected">foo</option></select>`).document.querySelector('select').value;
// undefined
```

**Comment by WebReflection** [comment]
It's up ... select.value and options.selected or options.value are up

**Comment by MadLittleMods** [comment]
Thanks for the quick update @WebReflection! Spotted a tiny issue with the new change: https://github.com/WebReflection/linkedom/issues/171

**Comment by WebReflection** [comment]
that's not an issue to me, explained in comments 👋
