### ISSUE TITLE
`<select>` should have a `value` setter

### ISSUE THREAD

**Issue by MadLittleMods** [WebReflection/linkedom#171]
`selectElement.value = 'bar';` throws an error in strict mode (`'use strict';`): `Uncaught TypeError: Cannot set properties of null (setting 'value')`. 

This error prevents the app from being server side rendered (https://github.com/matrix-org/matrix-public-archive/pull/101) in strict mode. Before https://github.com/WebReflection/linkedom/commit/155dfb9de84c672a0b2f4476d14f68d4b9a5054e, the app would render because the select element `getter` wasn't defined.

Expected:

```js
'use strict';
const { parseHTML } = require('linkedom');

parseHTML(`<select><option value="foo" selected="selected">foo</option></select>`).document.querySelector('select').value = 'bar';
// 'bar'
```

Actual:

```js
'use strict';
const { parseHTML } = require('linkedom');

parseHTML(`<select><option value="foo" selected="selected">foo</option></select>`).document.querySelector('select').value = 'bar';
// Uncaught TypeError: Cannot set properties of null (setting 'value')
```

To be clear, the DOM (`<option selected="selected">`) does not need to change. Just the `value` field of the select element.

**Comment by WebReflection** [comment]
the use case is no tintersting for this project ... as the main use case is to provide a fast output, not to use this library as a browser replacement ...there's JSDOM for that, here I was trying to be nice on the reading/crawling path ... probably my bad, happy to redraw my last changes.

**Comment by MadLittleMods** [comment]
@WebReflection Sounds reasonable. I originally opened https://github.com/WebReflection/linkedom/issues/170 because https://github.com/WebReflection/linkedom/issues/166 was accepted 👍

**Comment by WebReflection** [comment]
@MadLittleMods the thing is ... I don't care much about the writing path ... unless there are valid reasons ... the input case is different, as it doesn't involve extra options nested child checks, and I wonder what's the use case to justify that change ... why would you `select.value = ... ` in general even on a DOM native based page, and so on ... can you clarify what's the issue you are trying to solve here?

**Comment by MadLittleMods** [comment]
I think you're right. I was using `select.value = ...` as a crutch. I updated the app to swap around the `selected` attribute appropriately, https://github.com/matrix-org/matrix-public-archive/pull/102. Before it was trying to do that but didn't have the binding to actually update when the value changes.

I don't think it would be unreasonable to support `select.value = ...` like `input` but it's not a use case I have exact evidence for so not too worried about it at the moment.
