### ISSUE TITLE
Webpack warning Can't resolve 'canvas'

### ISSUE THREAD

**Issue by alexeychikk** [WebReflection/linkedom#172]
I am using this great package in V8 environment and building my sources with Webpack.
Webpack statically analyzes imports so it produces the following warning:
```
WARNING in ./node_modules/linkedom/commonjs/canvas.cjs 3:2-36
Module not found: Error: Can't resolve 'canvas' in 'app\node_modules\linkedom\commonjs'
```
I want to avoid this warning and to achieve that I can set an alias to the `canvas` package in my `webpack.config.js`.
The problem is I don't want to install any third-party `canvas` packages, I just don't need canvas, so I would like to point webpack to your fake `Canvas` implementation.
It would be great if you extracted this part
https://github.com/WebReflection/linkedom/blob/main/commonjs/canvas.cjs#L6-L16
into separate file so I can point my alias to this file and don't hit `try-catch` block.

**Comment by WebReflection** [comment]
nice and clean, thanks
