### ISSUE TITLE
window doesn't have a document

### ISSUE THREAD

**Issue by MathGeniusJodie** [WebReflection/linkedom#18]
is this by design? it breaks javascript written to be run client side in some cases

**Comment by WebReflection** [comment]
where is the code you tried?

```js
import {parseHTML} from 'linkedom';
const {window} = parseHTML('<div></div>');
console.log(window.document);
```

It's there. If you mean that there is no global window, you are in charge of polluting the global, this module never touches the global scope/context.

**Comment by MathGeniusJodie** [comment]
I might be doing something wrong, lemme report back

**Comment by WebReflection** [comment]
if you use `new DOMParser` instead be sure you retrieve the `defaultView` from the returned `document`, which is what `parseHTML` exposes directly

**Comment by MathGeniusJodie** [comment]
so when I use window.eval to run a script that uses "document", I get a `ReferenceError: document is not defined` error, but if I add `foo.window.document = foo.document` the script runs flawlessly

**Comment by WebReflection** [comment]
again, there is no global `document`, neither a global `window` ... you have to set it to the `globalThis` object yourself, if you need it, but it won't be done here.

**Comment by MathGeniusJodie** [comment]
great, thanks, I have a really janky setup to ssr pages that are meant to be client side, I don't expect my use case to be supported haha

**Comment by WebReflection** [comment]
You can export anything you like via the `document.defaultView` and attach stuff to the `global.document = ...` or `global.window = ...` and so on, which might be necessary in some setup with FE libraries that (*rightly*) give a public `document` for granted
