### ISSUE TITLE
Using linkedom in quickjs

### ISSUE THREAD

**Issue by mikeptweet** [WebReflection/linkedom#180]
I can't seem to find a way to use this module in quickjs ... does anyone have a quick sample that shows its usage?

thanks

**Comment by WebReflection** [comment]
the [worker.js](https://github.com/WebReflection/linkedom/blob/main/worker.js) file works in browsers envs ... it's meant to provide just the right amount of non-node-js related tooling ... have you tried that file in QuickJS?

**Comment by WebReflection** [comment]
P.S. .. that's a `require('linkedom/worker')` away .... or import

**Comment by mikeptweet** [comment]
Thanks ... worker.js does the trick :-)
