### ISSUE TITLE
looking advice on xhtml serialization

### ISSUE THREAD

**Issue by pkra** [WebReflection/linkedom#181]
This is more of a community question - please close it if it's not suitable here.

I use linkedom to create html that ends up being used both on the web as well as via the epub format (which requires xhtml). Ideally, I'd like to create a single linked-DOM and then serialize it both ways. Instead, I'm currently post-processing the html serialization.

I'm wondering if anyone has found a good way or has any insight into how best approach the problem from a linkedom point of view.

**Comment by WebReflection** [comment]
If you create an XML or XHTML output it should work and only post processing you need is doctype for html, have you tried that?

**Comment by pkra** [comment]
> If you create an XML or XHTML output it should work

I'm not sure I follow. With "output" do you mean something like in deep-dive.md? Or do you mean I should parse as `text/xml` and use its serialization? In that case I run into some node methods not being available (e.g., `insertAdjacentHTML`) (and I guess theoreticaly I might run into issues with void tags not being void behaving strangely in edge cases but that's less of a concern).

**Comment by WebReflection** [comment]
I don't have any code to look at so it's hard to understand what you are doing ... but if you do:

```js
const document = (new DOMParser).parseFromString('...', 'text/xml');
```

you have an XML document you can `document.toString()` and have self closing tags and friends ... although that might break with empty nodes if outputted as HTML ... so text/xhtml shouold do?

**Comment by pkra** [comment]
First of all: thanks for taking the time to respond. I know you have better things to do.

> I don't have any code to look at so it's hard to understand what you are doing 

Right, sorry about that. I was writing in a hurry. Roughly speaking: 

* I start with plain `(new DOMParser).parseFromString(htmlstring, 'text/html')` 
* do some work on the DOM.
* run `document.toString()` to serialize as HTML5
  * to ship to the browser
* do some more work on the DOM (to appease the epub gods)
* serialize again as HTML5
* convert that file to xhtml (with non-JS tooling)
  * to ship in an epub file

That extra conversion step is the annoying part (especially since the tool we use for that is buggy). 

In a full browser I'd do `(new XMLSerializer).serializeToString(document)` and be happy with that.

So I've actually tried throwing w3c-serializer (from the jsdom team) at a (linked) DOM - but that failed (afaict, due to namespace stuff which I don't think makes sense to add to linkedom). I have had success by abusing @xmldom/xmldom's serializer but that seems likely to backfire eventually. 

Maybe that's the right direction - keeping xml serialization separate - I just thought that since linkedom can serialize both ways already, I could find a shortcut.

**Comment by pkra** [comment]
I should also mention another obvious "hacky" alternative that didn't work out: parse as HTML, serialize, reparse (with linkedom) as xml or xhtml -- I feel like that should work but it fails for the typical obscure reasons. E.g., U+00A0 in the source string later gets serialized into `&nbsp;`  which then turns into `&amp;&nbsp;`. There also seems to be a linkedom bug: in XML, attribute values need more escaping than in HTML (& and < at least).

**Comment by pkra** [comment]
> There also seems to be a linkedom bug: in XML, attribute values need more escaping than in HTML (& and < at least).

Sorry, I think I'm wrong about that. It's just another one of the obscure problems -- it "should" lead to an XML parsing error to have unescaped stuff in attribute values.

**Comment by WebReflection** [comment]
Not sure I follow but the parser is not part of this project but also it’s not goal of this project to be fully specs compat … I still have zero code to even look at, so I won’t do any follow up until I can reproduce or understand the issue.

**Comment by pkra** [comment]
Thanks, I understand. I'm clearly failing to express myself. Thanks for taking the time and trouble. I'll post a follow up if I find the kind of solution I'm looking for.
