### ISSUE TITLE
Add `HTMLScriptElement.text`

### ISSUE THREAD

**Issue by regseb** [WebReflection/linkedom#182]
Hi,

The `HTMLScriptElement` class has a **[`text`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLScriptElement#htmlscriptelement.text)** property that returns the content of the element. This property isn't present in [script-element.js](https://github.com/WebReflection/linkedom/blob/ea41664/esm/html/script-element.js).

This message gives details about the `text` property: https://stackoverflow.com/a/34370879

**Comment by WebReflection** [comment]
could you use textContent until you land a PR to fix this?

**Comment by regseb** [comment]
The pull request #186 _added `text` attributes to `script`_. Can this issue be closed?

**Comment by WebReflection** [comment]
this happens when no issue is mentioned in the commit ... closing
