### ISSUE TITLE
Add `HTMLMetaElement.content`

### ISSUE THREAD

**Issue by regseb** [WebReflection/linkedom#183]
Hi,

The `HTMLMetaElement` class has a **[`content`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMetaElement/content)** property that returns the value of the `content` attribute. This property isn't present in [meta-element.js](https://github.com/WebReflection/linkedom/blob/1bad9bf/esm/html/meta-element.js).

**Comment by WebReflection** [comment]
pleas file a PR, thanks! There are examples on how to implement getters to any class and how to register classes too, if you need any guidance, I'd be happy to help.

**Comment by regseb** [comment]
This issue has been fixed with PR https://github.com/WebReflection/linkedom/pull/192 (https://github.com/WebReflection/linkedom/issues/191).
