### ISSUE TITLE
Ensuring the /cached export is detected by TypeScript

### ISSUE THREAD

**Issue by fabiospampinato** [WebReflection/linkedom#194]
It looks like the `/cached` export is not detected by TS:

```ts
import * as A from 'linkedom';
import * as B from 'linkedom/cached';
import * as C from 'linkedom/worker';
```

<img width="319" alt="Screen Shot 2023-03-09 at 18 34 45" src="https://user-images.githubusercontent.com/1812093/224122723-ab1396d0-edd9-4aea-ae2c-3072c6b13587.png">

I'm not exactly sure why, maybe a "types" property is required [here](https://github.com/WebReflection/linkedom/blob/e22febd73d226dd9310a9e530679f08fbe2491c7/package.json#L51).

**Comment by fabiospampinato** [comment]
It looks like `linkedom/worker` isn't detected when compiling the code 🤨 with a different error:

```
src/variants/cached.ts:4:25 - error TS2307: Cannot find module 'linkedom/cached' or its corresponding type declarations.

4 import {parseHTML} from 'linkedom/cached';
                          ~~~~~~~~~~~~~~~~~

src/variants/worker.ts:4:25 - error TS7016: Could not find a declaration file for module 'linkedom/worker'. '/Users/fabio/Code/fabiospampinato/linkedom-global/node_modules/linkedom/worker.js' implicitly has an 'any' type.
  If the 'linkedom' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'linkedom/worker';`

4 import {parseHTML} from 'linkedom/worker';
                          ~~~~~~~~~~~~~~~~~
```

**Comment by fabiospampinato** [comment]
Interestingly by disabling the implicit any check it stops complaining about `linkedom/worker`, but nothing changes for `linkedom/cached`.

```
{
  "compilerOptions": {
    "noImplicitAny": false
  }
}
```

**Comment by WebReflection** [comment]
I don't TS, I just use and code-cover all code to be sure it does what it's meant to be ... yet I think both cached and worker entries in package.json would work just fine using the very same default export type ... mind giving it a try?

**Comment by WebReflection** [comment]
P.S. this is to say every TS part of his project is out of contributions, as I am not even the best person to solve TS usses
