### ISSUE TITLE
querySelectorAll descends into template elements but should not

### ISSUE THREAD

**Issue by allain** [WebReflection/linkedom#202]
Hello. Thank you for this library. I've been starting to use it as the basis for a SSR solution and am putting it through its paces.

I've noticed a couple things:

`document.querySelectorAll('*')` returns all elements in the DOM even the ones in `template` elements which I believe should be ignored.

**Comment by WebReflection** [comment]
fixed 👍

**Comment by allain** [comment]
Thanks.

It looks like it's fixed as long as the template element is not the element on which `querySelectorAll` is being invoked.

I have to add targetEl.tagName !== 'TEMPLATE' on my code to work around it, which isn't a big deal but I figured I'd let you know since that's how chrome behaves.

**Comment by WebReflection** [comment]
that's a broken use case to me though ... why would you search inside a template if you know nothing should come up as answer? what's your use case?

**Comment by WebReflection** [comment]
P.S. let's also keep in mind for SSR having template working like any other node is a feature or just convenient so while I agree from outer elements point of view template content shouldn't directly be exposed, if you really want to handle template elements for SSR reasons you just can ... in short not sure that specific case is worth fixing, unless convinced otherwise.

**Comment by allain** [comment]
Sure. In my current code base I've managed to have the same code for the client side and server side rendering.

The `initTree` can be run on template tags but there's really no need for special case handling inside of it for them.

To work around the difference I'm doing the following to work around it:

```javascript
...
async initTree(targetEl) {
    await this._patchEl(targetEl)

    if (targetEl.tagName === 'TEMPLATE') return

    for (const child of targetEl.querySelectorAll('*')) {
      if (!child.closest('[x-ignore]')) {
        await this._patchEl(child)
      }
    }
  }
...
```

It's not a huge deal if you choose not to fix it since I've already for a fix in place. I may eventually replace it with TreeWalker anyhow because the 'x-ignore' check is not at all performant.

Thanks again.

**Comment by allain** [comment]
If anyone's interested I eventually went with this:

```javascript
 async initTree(targetEl) {
    const els = [targetEl]

    while (els.length) {
      const el = els.shift()

      await this._patchEl(el)

      if (el.tagName !== 'TEMPLATE' && !el.hasAttribute('x-ignore')) {
        els.push(...el.children)
      }
    }
  }
```
