### ISSUE TITLE
NBSP Chars Escaped Incorrectly for XML Documents

### ISSUE THREAD

**Issue by jordandh** [WebReflection/linkedom#205]
### Explanation
I am no xml expert so forgive me if I am wrong but I believe NBSP characters should be escaped as `&#160;` in xml documents because `&nbsp;` is not defined in xml. There are a small number of named entities defined in xml but nbsp is not one of them according to the docs here https://www.w3.org/TR/xml11/#sec-predefined-ent

### Problem
nbsp chars are encoded as `&nbsp;` for xml documents

### How should it behave?
If the document is an xml document then nbsp chars should be encoded as `&#160;`

**Comment by WebReflection** [comment]
fixed and landed
