### ISSUE TITLE
Support getInnerHtml() for SSR of declarative shadow DOM

### ISSUE THREAD

**Issue by ttraenkler** [WebReflection/linkedom#210]
linkedom would be a great fit for lightweight SSR of web components, missing only ```Element.getInnerHTML()```. [Here](https://gist.github.com/developit/54f3e3d1ce9ed0e5a171044edcd0784f) is a polyfill that might serve as a starting point for an implementation.

For server side rendering of web components, [declarative shadow DOM](https://developer.chrome.com/articles/declarative-shadow-dom/) has recently been standardized and [shipped](https://caniuse.com/?search=declarative%20shadow%20dom) in all major browsers except Firefox, [Mozilla's position being positive](https://github.com/mozilla/standards-positions/issues/335) on this feature as well.

Similar to ```Element.innerHTML```, the new function ```Element.getInnerHTML()``` will [serialize DOM elements including the shadowroots of custom elements](https://github.com/mfreed7/declarative-shadow-dom#serialization) which are skipped by innerHTML. In essence, wherever a ```<custom-element>``` is found in the DOM, the corresponding template will be inlined with ```<template shadowrootmode="open">``` (note this was recently renamed from shadowroot="open" which the above mentioned polyfill still uses).

Instead of
```ts
element.innerHTML
```
producing
```html
   <custom-element>
      <h2>light content</h2>
    </custom-element>
```
the new function
```ts
element.getInnerHTML({includeShadowRoots: true})
```
will include the shadowroot
```html
   <custom-element>
      <template shadowrootmode="open">
        <p id="a">shadow a</p>
        <p id="b">shadow b</p>
        <p id="c">shadow c</p>
        <slot></slot>
      </template>
      <h2>light content</h2>
    </custom-element>
```

**Comment by WebReflection** [comment]
where would the content of that shadowroot be taken from?

**Comment by WebReflection** [comment]
also, what happens with mode `closed` ?

**Comment by ttraenkler** [comment]
The polyfill I linked in the OP contains code to deal with open and closed shadowroots. 

> where would the content of that shadowroot be taken from?

For open shadowroots simply from the element's ```this.shadowRoot```.

> also, what happens with mode `closed` ?

For closed you pass the closed shadowroots to the getInnerHTML function explicitly as an array. Here is a description from the champion of the proposal that explains it: 

_Closed shadow roots
To allow serialization of closed shadow roots, an additional option will be added:

const html = element.getInnerHTML({ includeShadowRoots: true, closedRoots: [shadowRoot1,shadowRoot2,...] });
Using this syntax, if any of the closedRoots shadow roots are encountered during serialization, they will be serialized regardless of whether they are open or closed. Closed shadow roots will be serialized using <template shadowrootmode="closed">._
https://github.com/mfreed7/declarative-shadow-dom

Note I found a package called [ocean](https://github.com/matthewp/ocean) for web components SSR which claims: _"Ocean's DOM shim is backed by [linkedom](https://github.com/WebReflection/linkedom), a fast DOM layer. The shim also bridges compatibility with popular web component libraries."_ even though I cannot find a reference to it in the implementation - maybe it's outdated. However maybe it is a good reference or point for collaboration on the implementation details.

**Comment by ttraenkler** [comment]
I have discussed getInnerHTML with @mfreed7 the champion of the proposal and it seems it is not yet standardized. The implementation in Chromium is outdated and deprecated but so far without an alternative until there is consensus across vendors. He referenced these issues:

- https://github.com/whatwg/html/issues/8867
- https://github.com/whatwg/html/pull/5465

Until standardized it is probably better to not add getInnerHTML and instead add a mode configuring wether the custom Node.toString method of linkedom will include shadowroots when serializing the DOM tree to an HTML string. 

Since it's unclear what will be standardized it's best to keep it outside of DOM APIs in a custom mode parameter of linkedom. I will come up with a new proposal that is minimally invasive since I think it's a common need for serializing web components that it's better to have this as part of the toolbelt inside of linkedom.
