### ISSUE TITLE
Element style iteration works only after explicitly reading from it

### ISSUE THREAD

**Issue by omril1** [WebReflection/linkedom#219]
It seems that iterating on an element's style iterates 0 times while it clearly shows that it has content.
After explicitly reading a property from the style or stringifying it would iterate properly on the contents of the style.

Reproduction:
```js
const linkedom = require('linkedom');

const parser = new linkedom.DOMParser();
const e = parser.parseFromString('<html><body><div style=" display:  flex ;"></div></body></html>', 'text/html');

const divWithStyle = e.body.firstChild;

console.log(divWithStyle.hasAttribute('style')); // true
console.log(divWithStyle.getAttribute('style')); // ' display:  flex ;'
console.log(divWithStyle.style); // CSSStyleDeclaration(0) [Map] {}
console.log([...divWithStyle.style]); // []                      <------- problem
console.log(Array.from(divWithStyle.style)); // []               <------- problem
divWithStyle.style.toString();
// divWithStyle.style.display; works as well
console.log([...divWithStyle.style]); // ['display']             <------- works
console.log(Array.from(divWithStyle.style)); // ['display']      <------- works
```

Verified on version 0.14.25 and 0.15.2

workaround, perform a `toString()` on the style before iterating on it

**Comment by omril1** [comment]
I believe it's because the `toString()` is calling `updateKeys(self);` 

https://github.com/WebReflection/linkedom/blob/cecb1a511301c2b2f2aa8636796559b81f6f195f/esm/interface/css-style-declaration.js#L112-L114


Adding `UpdateKeys(self)` to the iterator method fixes the issue

**Comment by WebReflection** [comment]
PR welcome, thank you!

**Comment by WebReflection** [comment]
it's up and running https://github.com/WebReflection/linkedom/pull/220
