### ISSUE TITLE
Bug?: window.navigator is undefined

### ISSUE THREAD

**Issue by haikyuu** [WebReflection/linkedom#23]
First, thanks for your great work on this project.

While using Linkedom for testing a React app, I've come across this error: `TypeError: Cannot read property 'userAgent' of undefined`

And it comes from `window.navigator` being undefined.

Here is [how it's defined in JSDOM](https://github.com/jsdom/jsdom/tree/master/lib/jsdom/living/navigator). For the scope of linkedom, and since it's a read only property, I think providing a default value to avoid crashes is enough for a fix.

Try it here https://runkit.com/haikyuu/60259abfa573fe0019c29a12

**Comment by WebReflection** [comment]
to clarify, I am not planning to bring in all *JSDOM* things, as I couldn't care less ... there's *JSDOM* for bloated, unrelated SSR things, so your hint about a default sounds fair ... and then again, which one should that be?

**Comment by WebReflection** [comment]
I have the answer: mine 🥳

**Comment by haikyuu** [comment]
Thanks @WebReflection 

JSDOM scope is huge and it would be unreasonable to try to match that.

But I really enjoy my experience using linkedom vs JSDOM. So the next PR is on me
