### ISSUE TITLE
cdata-section beaks esm import

### ISSUE THREAD

**Issue by jefbarn** [WebReflection/linkedom#234]
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.../linkedom/esm/interface/cdata-section' imported from .../node_modules/linkedom/esm/shared/facades.js

The facades.js file needs the cdata import to have the '.js' extension.

https://github.com/WebReflection/linkedom/blob/6f21a9df53e12431a1a38f0974c69b4fb9ee57ce/esm/shared/facades.js#L3C74-L3C74

**Comment by bartveneman** [comment]
Having the same issue in 0.16.0. Version 0.15.6 is not affected by this issue.

**Comment by WebReflection** [comment]
damn it TS users ...

**Comment by WebReflection** [comment]
apologies I should've paid more attention, not even sure why tests pass there ... fixed now.

**Comment by WebReflection** [comment]
> not even sure why tests pass there

FWIWI actually I know why, CJS does the same, it fallsback to `.js` so no problems whatsoever there ... bummer, this should've been caught earlier. Sorry again.

**Comment by WebReflection** [comment]
OK, this should never happen again.

**Comment by bartveneman** [comment]
Hey, no worries, thanks for the quick fix + tests!
