### ISSUE TITLE
getElementsByName is missing

### ISSUE THREAD

**Issue by asportnoy** [WebReflection/linkedom#236]
[Per MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByName), `document.getElementsByName` should return a `NodeList` of all elements whose `name` attribute matches the input. This method is included in the type definition for document, but it is not actually implemented anywhere.

[JSDOM's implementation of getElementsByName](https://github.com/jsdom/jsdom/blob/a39e0ec4ce9a8806692d986a7ed0cd565ec7498a/lib/jsdom/living/nodes/Document-impl.js#L498-L505)

**Comment by WebReflection** [comment]
no live collections here, use JSDOM if you want a 1:1 browser behavior.
