### ISSUE TITLE
[BUG] initEvent canBubble = true should change the event to bubble

### ISSUE THREAD

**Issue by Havunen** [WebReflection/linkedom#239]
`event.initEvent` method canBubble -argument should make the event bubble when true

Currently it does nothing

**Comment by WebReflection** [comment]
there's no interest in this project to be a JSDOM replacement ... for SSR events don't really matter and I am not sure why they should. That being said, if the PR won't affect performance anyhow to anything else it'll be more than welcome, but I don't have neither interest nor time to work on this, sorry.
