### ISSUE TITLE
Tests pass with unhandled rejections in node 14 and node 12

### ISSUE THREAD

**Issue by haikyuu** [WebReflection/linkedom#24]
Tests do pass but unhandled rejections are there in console. You can see that [here](https://travis-ci.org/github/haikyuu/linkedom/jobs/758659588)

**Comment by WebReflection** [comment]
then tests don't pass, right? ... interesting, no idea why I wouldn't see this in node 15, will check it, thanks.

**Comment by WebReflection** [comment]
found it ... neither node 14 nor 12 have `Event` interface, and the `@ungap` polyfill relies on a global document ... bummer

**Comment by haikyuu** [comment]
found that too but I was unsure what to do with ungap. Maybe just copy it in the source and refactor it to use a document parameter?

**Comment by WebReflection** [comment]
naa, I've dropped one dependency, which feels *way* better 🥳

**Comment by haikyuu** [comment]
😆  I like that commit message `Poorlyfill`
