### ISSUE TITLE
Illegal constructor when extending DocumentFragment

### ISSUE THREAD

**Issue by mary-ext** [WebReflection/linkedom#255]
Extending DocumentFragment is used by [`@github/template-parts`](https://github.com/github/template-parts/blob/8f38806c6cf7e77d2d07c0316a2c970284120afe/src/template-instance.ts#L43) and [`document-persistent-fragment`](https://github.com/WebReflection/document-persistent-fragment/blob/0cdbeffd48476df5f74b0a9bbd47c591e5b8c986/esm/document-persistent-fragment.js#L22)

Using these in linkedom causes Illegal constructor error being thrown, even though the browser and JSDOM handles this just fine.

**Comment by WebReflection** [comment]
JSDOM pollutes the global or assume there's only one document on the global, which is nonsense in here ... almost every class in here requires the `ownerDocument` as first argument so you can bind the class passing your `document` reference and be good with it.

P.S. document-persistent-fragment is not needed anymore, I've found a way better solution in latest *uhtml* library and I might soon just publish that as module a part where no global patch is ever needed.
