### ISSUE TITLE
`querySelectorAll` breaks when the DOM contains an element with a 'template' attribute

### ISSUE THREAD

**Issue by omril1** [WebReflection/linkedom#262]
```js
const html = parser.parseFromString(`<div template="this content breaks querySelector">😊</div>`, 'text/html').documentElement;

html.querySelectorAll('*'); // throws TypeError: Cannot read properties of undefined (reading 'nodeType')
```

The cause seems to be `next = next.localName === 'template' ? next[END] : next[NEXT];`

I assume the check with `localName` should happen only if `next` is an `ELEMENT_NODE` and not an attribute as the code there was meant for template elements

**Comment by WebReflection** [comment]
It's up, thank you 👋
