### ISSUE TITLE
"perf_hooks" and "canvas" not found issue with using linkedom

### ISSUE THREAD

**Issue by sagarchoudhary96** [WebReflection/linkedom#265]
<img width="737" alt="Screenshot 2024-03-19 at 6 24 26 PM" src="https://github.com/WebReflection/linkedom/assets/16102594/86ecf155-8831-472f-8632-6fd45637d6fc">

<img width="746" alt="Screenshot 2024-03-19 at 6 26 01 PM" src="https://github.com/WebReflection/linkedom/assets/16102594/e79989c6-304a-4110-be33-1b2b59508e07">

 Getting these errors while trying to use linkedom `parseHTML` method  within nextjs api routes.

**Comment by MohitKS5** [comment]
Why did you close it ? Was there a fix ?

**Comment by WebReflection** [comment]
@MohitKS5 no but it's a duplicate: https://github.com/WebReflection/linkedom/issues/249
