### ISSUE TITLE
HTMLAnchorElement loses `rel` attribute after casting to string

### ISSUE THREAD

**Issue by what1s1ove** [WebReflection/linkedom#274]
Hi there!
Thank you for such a wonderful package!

Here is the problem:

```js
let window = parseHTML(`
<!DOCTYPE html>
<html>
  <body><a href="https://www.google.com/">Google</a></body>
</html>
`)

let linkNode = window.document.querySelector(`a`)

linkNode.target = `_blank`

linkNode.rel = `noreferrer noopener` // losses `rel` attribute after casting to string

console.log(window.document.toString())
//  <html>
//    <body><a target="_blank" href="https://www.google.com/">Google</a></body>
//  </html>


linkNode.setAttribute(`rel`, `noreferrer noopener`) // works as expected 

console.log(window.document.toString())
//  <html>
//    <body><a rel="noreferrer noopener" target="_blank" href="https://www.google.com/">Google</a></body>
//  </html>
```

`HTMLAnchorElement[rel]` is not the read-only attribute according to the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/rel), so I think it should behave the same as `setAttribute('rel', // ...)`

**Comment by what1s1ove** [comment]
> Yup, nothing in here indeed: https://github.com/WebReflection/linkedom/blob/main/esm/html/anchor-element.js ... mind a PR?

Hey @WebReflection ! Thank you for the answer!

I will take a look today a bit later 🙏

**Comment by WebReflection** [comment]
I should probably have a script that vomits out per each class accessors so that it's easy to have a list and compare/fix all nodes with special treatment ... until then though ... this is a copy & paste of `target` or `type`, it should be an easy PR

**Comment by what1s1ove** [comment]
> I should probably have a script that vomits out per each class accessors so that it's easy to have a list and compare/fix all nodes with special treatment ... until then though ... this is a copy & paste of `target` or `type`, it should be an easy PR

Sure! I've been busy with other projects, but I've just created a [PR](https://github.com/WebReflection/linkedom/pull/276) 🙂
