### ISSUE TITLE
CharacterData's `data` should be mutable

### ISSUE THREAD

**Issue by natemoo-re** [WebReflection/linkedom#29]
Hello there—thanks for this library! I ran into some issues when attempting to use Preact with `linkedom`, which the Preact team was able to track down to an unhandled edge case with `CharacterData`.

According to [this section](https://dom.spec.whatwg.org/#concept-cd-data) of the DOM spec:
> Each node inheriting from the CharacterData interface has an associated mutable string called **data**.

It looks like `data` isn't mutable at the moment. I think all that needs to be added is a setter below `CharacterData`'s [`get data()`](https://github.com/WebReflection/linkedom/blob/096baa7bab240dac9249201131480c7bd990f1ef/esm/interface/character-data.js#L50).

**Comment by WebReflection** [comment]
interesting ... *React* uses `nodeValue`, I use `textContent`, now *Preact* uses `data` ... we should really meet at the pub and discuss our opinions here 😂

**Comment by WebReflection** [comment]
Fixed, up, and running 👋

**Comment by marvinhagemeister** [comment]
In the DOM spec the `.textContent` property [returns the value of `.data`](https://dom.spec.whatwg.org/#dom-node-textcontent) under the hood. The same is true for [`nodeValue`](https://dom.spec.whatwg.org/#dom-node-nodevalue).

**Comment by WebReflection** [comment]
that's not what I've investigated though ... it looks like everything passes through `nodeValue` instead, while `textContent` is a switch statement away from setting the value.

https://chromium.googlesource.com/chromium/blink/+/master/Source/core/dom/Node.cpp#1268

actually WebKit uses `data()` indeed: https://webkit.googlesource.com/WebKit/+/master/Source/WebCore/dom/Node.cpp#1398

interesting, will dig more and find *where* it's more convenient to use `.data` instead, thanks

**Comment by WebReflection** [comment]
oops, nope, all `setData` even in webkit https://webkit.googlesource.com/WebKit/+/master/Source/WebCore/dom/Node.cpp#1590 not sure what that does though 🤔

**Comment by WebReflection** [comment]
OK, FWIW, everything passes through `setData`, including `setNodeValue`, which is indeed an unnecessary indirection. Thanks, I think I'll move character data logic for content inside data then
