### ISSUE TITLE
ARIA properties do not exist

### ISSUE THREAD

**Issue by midnightveil** [WebReflection/linkedom#291]
From linkedom:
```js
import { parseHTML, HTMLClasses } from "linkedom";
const { document } = parseHTML("");

const a = document.createElement("a");
a.ariaCurrent = "page";
a.className = "test";
console.log(a.toString());
// Prints: <a class="test"></a>
```

In a browser console (with the adjustment for printing)
```js
const a = document.createElement("a");
a.ariaCurrent = "page";
a.className = "test";
console.log(a);
// Prints <a class="test" aria-current="page">
```

https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaCurrent

Is there a way to monkey patch these in somehow?

**Comment by WebReflection** [comment]
You can add those to HTMLElement class following this page https://github.com/WebReflection/linkedom/blob/main/how-to-contribute.md#what-about-attributes-accessors ... there are PRs that contributed to accessors too

**Comment by WebReflection** [comment]
this is one of those ... it's a whole new element, what you should do, it's just add accessors to the HTMLElement class:
https://github.com/WebReflection/linkedom/pull/282

You have tons of other accessors examples in there too: https://github.com/WebReflection/linkedom/blob/main/esm/html/element.js#L28 aria is missing as accessors
