### ISSUE TITLE
Events are not supported

### ISSUE THREAD

**Issue by haikyuu** [WebReflection/linkedom#33]
When using LinkeDOM for testing, I stumbled across this limitation:
```
input.dispatchEvent(new window.InputEvent("change", { data: "filter" }));
```

This errors since `InputEvent` is undefined.

**Comment by WebReflection** [comment]
you can extend event and change the dance to init it:
https://github.com/WebReflection/linkedom/blob/main/esm/interface/event.js

but yeah, `InputeEvent` is not there yet, and I am not planning to fully implement it neither, as the range bit on SSR has no meaning.

Also be aware that I don't know if events bubbles up ... it's using native Event from NodeJS, where available, and I am not sure I should diverge from those.

**Comment by haikyuu** [comment]
I've tried the following code and it is working
```
    const event = new window.Event("build");

    // Listen for the event.
    filter.addEventListener(
      "build",
      function (e) {
        console.log("built");
      },
      false
    );

    // Dispatch the event.
    filter.dispatchEvent(event);
```
The event listener is called successfully.

**Comment by WebReflection** [comment]
Events *are* there already and test-covered ...

**Comment by haikyuu** [comment]
That's good. I'll try more scenarios to see if I can use `Event` instead of `InputEvent` and get it to work in my setup.

**Comment by WebReflection** [comment]
OK, I've added it ... but `ranges` won't work, the rest looks fine.

**Comment by haikyuu** [comment]
Thanks a lot @WebReflection
