### ISSUE TITLE
Performance over native DOM

### ISSUE THREAD

**Issue by Nashorn** [WebReflection/linkedom#35]
Not an issue but a question. Is Linkedom faster at navigating the DOM compared to native use of querySelector/DOM.?

**Comment by WebReflection** [comment]
great question ... so this is a copy and paste of [the current benchmark file](https://github.com/WebReflection/linkedom/blob/main/test/benchmark/content.js) in latest Chromium console, for the [HTML Living Standard page](https://html.spec.whatwg.org/), which is **a 12MB document**.

![Screenshot from 2021-02-24 16-24-10](https://user-images.githubusercontent.com/85749/109023407-0cc3ff00-76bd-11eb-9edd-902f00257ddb.png)

While this is a screenshot of the very same document benchmarked via:
```sh
node test/benchmark/linkedom.js --html
```

![Screenshot from 2021-02-24 16-28-11](https://user-images.githubusercontent.com/85749/109023843-6cbaa580-76bd-11eb-986d-c1a0721b7ba9.png)

Of course the local benchmark also have *heap* memory snapshots, meaning it instruments the engine to measure that, which *might* as well be a *non-production-like* result.

A few takes:

  * this is a *JS* library, not something compiled and optimized for 20 years like a browser
  * parsing time is unfair, for the previous reason
  * normalize is done internally too, for the previous reason
  * crawling childNodes and children here is *much* faster
  * cloning the tree is 3x slower
  * DOM manipulation is 10x faster in here, at least in removing
  * cloning smaller tree is 2x slower in here
  * both outer and inner HTML operations are 3x slower here

... and I ain't even mad ...

### Cached results:

```sh
node test/benchmark/linkedom-cached.js --html
```

  * crawling children, or childNodes, is 2x faster in here
  * querying the document for the same selector more than once it's `0` time here
  * removing nodes is still much faster

... and I ain't even mad ...

I hope this answered 😊

**Comment by Nashorn** [comment]
Wow, awesome. I'll review this. 
On a sidenote, ran npm uninstall jsdom today. 45 PACKAGES REMOVED. !!!
