### ISSUE TITLE
serialize empty attributes for xml

### ISSUE THREAD

**Issue by Allam76** [WebReflection/linkedom#36]
First of all a very big thank you for a wonderful project! I thoroughly enjoy working with it.

I wonder if serialization of empty attributes should not depend on target (xml/html).

Consider ```console.log((new DOMParser).parseFromString(`<test hello=""></test>`,"text/xml").toString());```
vs ```console.log((new DOMParser).parseFromString(`<test hello=""></test>`,"text/hmtl").toString());```

in both cases the output is empty attribute: ```<test hello></test>``` which is correct html but not correct xml. Maybe the toString() method of attr.js should be dependant on target html or xml?

For now, i monkey patch with ```toString("text/xml")``` in the xml scenario.

Many thanks
Martin

**Comment by WebReflection** [comment]
didn't know XML would break there, so it looks like a bug indeed.

**Comment by WebReflection** [comment]
Fixed, thanks 👋

**Comment by nyanrus** [comment]
currently it's not fixed in "hidden" attribute

```
import {DOMParser} from "linkedom"

console.log((new DOMParser).parseFromString(`<test hidden=""></test>`,"text/xml").toString());
console.log((new DOMParser).parseFromString(`<test hidden=""></test>`,"text/html").toString());
/* outputs
<?xml version="1.0" encoding="utf-8"?><test hidden />
<test hidden></test>
*/
```

**Comment by WebReflection** [comment]
@nyanrus this has been fixed already? 🤔

**Comment by nyanrus** [comment]
oh it's not the issue
ok I will make new issue

**Comment by WebReflection** [comment]
@nyanrus it was the issue ... it was supposed to be fixed too ... I have no idea where that commit ended up butr it was broken. I've re-fixed this again, I hope this time it's fine.
