### ISSUE TITLE
Encountered issue with empty document ""

### ISSUE THREAD

**Issue by Nashorn** [WebReflection/linkedom#37]
After replacing jsdom with linkedom, i ran into issues where documents being sent into linkedom was throwing errors because some html are blank strings. I had to wrap in try{} and return a default blank document.

Not sure why, but JSDOM handled it somehow. I dont know how, its too late, its gone from my system

**Comment by WebReflection** [comment]
Why you need anything out of a blank string would be my counter bug for you ... closing, as not interested in such sloppy env.

**Comment by Nashorn** [comment]
Building a tool that consumes HTML generated from a content mgt system, no control over crap data

**Comment by WebReflection** [comment]
then use `parseHTML(data || "<html />")` ? I honestly don't know what to do with an empty string

**Comment by WebReflection** [comment]
OK, `(new DOMParser).parseFromString('', 'text/html')` doesn't break ... I'll re-open this then.

**Comment by WebReflection** [comment]
document returned on empty string 👋

**Comment by Nashorn** [comment]
Pulling latest, big thanks for re-opening. And yea, i have no control over very crappy data (html and css) being pulled into the tool i am building. This will help.
