### ISSUE TITLE
Uncaught SyntaxError: Octal escape sequences are not allowed in template strings.

### ISSUE THREAD

**Issue by Nashorn** [WebReflection/linkedom#38]
I never got this error with JSDOM, i feel it's important to file the bug since I am using Linkedom as a dropin.  I went back today to pull in a site into the tool which then uses linkedom to manipulate. It turns out that this HTML previously worked with jsdom, but now breaks in Linkedom, again, no control over the crappy html.

ERROR:
```Uncaught SyntaxError: Octal escape sequences are not allowed in template strings.```

Clicking on the error took me to the place in the HTML src that i am feeding into Linkedom, and it shows this (chopped snippet for brevity):
```footer:before,blockquote small:before{content:"\2014   \A0"}```

Thats just a part of inline css in a <style> tag in HEAD

Any idea?

**Comment by Nashorn** [comment]
UPDATE:
I can replicate using:
```var dom = new JSDOM(`<html><head><style>footer:before,blockquote small:before{content:"\2014 \A0"}</style></head></html>`);```

**Comment by Nashorn** [comment]
Even stranger, in my tool, i am not wrapping with ` back-ticks. I am literraly loading the HTML src from disk as 1 string and sending it right into new JSDOM(strHTML)

**Comment by WebReflection** [comment]
an *Uncaught SyntaxError: Octal escape sequences are not allowed in template strings.* is **not** about this library, it's about JS.

**Comment by WebReflection** [comment]
if you are using *eval* or *Function*, there you have the *JS* issue.

**Comment by WebReflection** [comment]
to clarify, you don't need this library to have that error:

```js
`\2014`
```

closing, as there's literally nothing I can do here: it's a Syntax Error, not a library issue ... and yes, you'll have the same syntax error in JSDOM, in everything *JS*, really.
