### ISSUE TITLE
DOM API Parity bug: appendChild *must* remove the node from the previous parent's childNodes

### ISSUE THREAD

**Issue by eordano** [WebReflection/linkedom#43]
Hi there! First of all, I wanted to say thank you for building this lib -- looks super useful. I stumbled upon it while trying to replace `jsdom` because of its 100 dependencies. Please feel free to close this issue if replacing `jsdom` is not an actual goal of this lib.

I'm trying to combine `linkedom` with `@mozilla/readability`. [Line 1251 of Readability.js](https://github.com/mozilla/readability/blob/master/Readability.js#L1251) in particular got me into an infinite loop. Rehashing the critical lines, the code looks like this:

```
while (someElement.childNodes.length) {
  anotherElement.appendChild(someElement.childNodes[0])
}
```

At first, I was a little confused about this, how can `length` change... but from [the appendChild](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild) documentation, it seems like the DOM implementation updates the array of the previous parent's childNodes -- thus the length of the array with children gets reduced over time.

Maybe I should suggest a patch to the maintainers of `@mozilla/readability`? In any case, I wanted to let you know of this potential incompatibility! Again, thank you for all the awesome.

**Comment by WebReflection** [comment]
the `node.remove()` is called in here, so I wonder if you are using the cached version or not, as the `childNodes` [is a getter](https://github.com/WebReflection/linkedom/blob/main/esm/mixin/parent-node.js#L53-L61), hence computed each time ... that means, if you trap `childNodes` once, you'll have issues, but if you don't, as your while loop suggest, everything should be fine ... in any case, it's not a goal so far of this library to fully reflect live collections, as there are more a mistake than a feature of the platform, indeed listed as legacy in the specification itself.

**Comment by WebReflection** [comment]
so, yeah https://github.com/mozilla/readability/blob/master/Readability.js#L1249-L1252

```js
var children = articleContent.childNodes;
while (children.length) {
  div.appendChild(children[0]);
}
```

live collections ... a legacy mess of the platform ... a few ways to solve that (also a more common way)

```js
// use append
div.append(...articleContent.childNodes);

// or use firstChild
while (articleContent.firstChild) {
  div.appendChild(articleContent.firstChild);
}

// or use a for loop over a slice
var children = [].slice.call(articleContent.childNodes);
for (var i = 0; i < children.length; i++)
  div.appendChild(children[i]);
}
```

In few words, live collections are bad, perform poorly, and usually are a footgun so I don't think this will ever land in LinkeDOM, hence I suggest you file that issue, while I'll put this different behavior in the README, or think if live collections should re-evaluate each time their length each time length is accessed ... but it's a bit *meh*, imho

**Comment by WebReflection** [comment]
@eordano I've updated the README with a *FAQ* session https://github.com/WebReflection/linkedom#faq

this is the first *FAQ* worth it a top place in there, but I hope it's clear what's going on, and why *LinkeDOM* here doesn't plan to support that.

**Comment by eordano** [comment]
Thank you!
