### ISSUE TITLE
Order of attributes reversed

### ISSUE THREAD

**Issue by qwtel** [WebReflection/linkedom#46]
Minimal example:

```js
parseHTML(`<body id="foo" class="bar"></body>`).document.toString())
```

produces:

```html
<body class="bar" id="foo"></body>
```

Similarly, the `.attributes` getter will return them in reversed order as well.

I've tried to fix this, however this causes a significant amount of tests to fail, so I'm not sure the extent to which this is behaviour is intended?

**Comment by WebReflection** [comment]
that's inevitable and it won't change. You can understand more about how this works in this video:
https://www.youtube.com/watch?v=PEESaD7Qkxs

as IE has been shuffling artributes forever and the order of attributes is practically irrelevant, please don't try to file an MR as the linked list approach is what makes attributes like that, but also where it shines in performance.

**Comment by qwtel** [comment]
Ah I see. I suspected somthing like this, thanks for clarifying!

**Comment by WebReflection** [comment]
Just had some “shower thought” about this ... as I’ve recently changed the parser and loop all attributes at once, I could as well loop backward.
That preserve the layout, although adding new attributes will “pretend” and I’m not sure about jsdon serialization ... now is at least always consistent.
But before I change anything: does the attributes order really matter?

**Comment by qwtel** [comment]
No, not that much. This would be more of a "nice-to-have" property.

**Comment by WebReflection** [comment]
Well, in such case I prefer consistency and performance, over "*nice to have*". I hope you don't mind 👋

**Comment by WebReflection** [comment]
Reopening as I've found a way to make sense of this order without penalizing performance. New attributes are still inserted at the beginning of the node, but there's no reason to invert the order on parsing.

**Comment by WebReflection** [comment]
Done, order preserved.

**Comment by qwtel** [comment]
Wow, very cool. 

BTW, in case you're interested, I'm using linkedom for this https://github.com/worker-tools/parsed-html-rewriter

**Comment by qwtel** [comment]
With this patch, it will match the original even closer.
