### ISSUE TITLE
Expose top-level toJSON export as alternative to the non-spec .toJSON method

### ISSUE THREAD

**Issue by ggoodman** [WebReflection/linkedom#47]
## Request

Expose a top-level `toJSON` method that accepts a `linkedom` element instance and returns that element's `jsdon` serialization.

## Use-case

When using `linkedom` in a TypeScript environment, element instances (including the `document`) don't seem expose a `.toJSON()` method. An exploration of the code suggests that this might be because the built-in `dom` typings from TypeScript are being used for these specced interfaces.

To serialize a `linkedom` element to its `jsdon` equivalent, the element needs to be cast to something like `any` before calling `.toJSON`. While this isn't a _huge_ problem, I think there's an opportunity to expose a mirror to the existing `parseJSON` top-level method that accepts a `linkedom` element and simply calls that element's `.toJSON()` method in a type-friendly way. This would allow us to continue pretending that these elements are the 'real deal'.

**Comment by WebReflection** [comment]
what's the TypeScript JSON format declaration? `any[]` ?

**Comment by WebReflection** [comment]
Never mind, I hope this works, but I don't TS much, so if there's any improvement I could do, please let me know, thank you 👋
