### ISSUE TITLE
window.addEventListener not available when running in node environment

### ISSUE THREAD

**Issue by chestozo** [WebReflection/linkedom#48]
Hello )
Is it expected that `window.addEventListener` is not available in node env?

Here is my snippet:
```js
const html = `
<!DOCTYPE html>
<html>
<head></head>
<body></body>
</html>
`
const { parseHTML } = require('linkedom')
console.log('linkedom: ', parseHTML(html).window.addEventListener)

const { JSDOM } = require('jsdom')
const dom = new JSDOM(html)
console.log('jsdom: ', dom.window.addEventListener)
```

running this code with `node` results into:
```
linkedom:  undefined
jsdom:  [Function: bound addEventListener]
```

What I am trying to do is to use `linkedom` together with jest similarly to how it is used in `jest-environment-jsdom` https://github.com/facebook/jest/blob/master/packages/jest-environment-jsdom/src/index.ts

**Comment by WebReflection** [comment]
I was almost like "*uhm ... OK*" ... then I've seen [this](https://github.com/facebook/jest/blob/master/packages/jest-environment-jsdom/src/index.ts#L64-L84). The window is a proxy with accessors, overwriting globals doesn't look like good design there.

Will think about it.

**Comment by chestozo** [comment]
🙏 grazie!

**Comment by WebReflection** [comment]
0.6.1 should work (at least that bit, I am sure there will be more changes needed).

**Comment by chestozo** [comment]
wow that was super quick! thank you a lot!!!
will try it out )

**Comment by chestozo** [comment]
yep ) now stuck at this point
https://github.com/facebook/jest/blob/master/packages/jest-environment-jsdom/src/index.ts#L128-L133
that is needed to execute scripts in context of the document.
=)

**Comment by WebReflection** [comment]
I don't know what that is but linkedom will never execute JavaScript in the page, resolve scripts src, or understand inline JS handlers or events ... there's JSDOM if you need that, this project won't care about replicating what a browser does, sorry.

**Comment by chestozo** [comment]
totally understandable ) thank you again!
