### ISSUE TITLE
Low priority: Entity encoding of quotes in attribute values

### ISSUE THREAD

**Issue by cramforce** [WebReflection/linkedom#49]
Hey,

It is pretty common (and this is how JSDOM behaves) for HTML serializers to allow special-casing the single quote `'` to not be encoded when using double-quote `"` as the attribute value delimiter.

While the current behavior works perfectly fine, it does make quote-heavy content like CSPs or SVG-data-URIs very busy to read.

Thanks!

**Comment by WebReflection** [comment]
arguably, for attributes the only thing I should encode is likely the `"` and nothing else ... as example, I think URLs might be broken now, if query strings parameters are in.

Thanks for the issue, will check ASAP.

**Comment by WebReflection** [comment]
It's up 👋

**Comment by cramforce** [comment]
You rock!
