### ISSUE TITLE
Could be used with jest as jsdom replacement?

### ISSUE THREAD

**Issue by stephenh** [WebReflection/linkedom#50]
Hey! I came across linkeddom today while googling for "faster jsdom" alternatives.

Specifically I'm looking to speed up our react application's Jest test suite, and wondering if you have any experience / tips doing that with linkedom? 

The comment in your blog post "I am already replacing every repository of mine that uses, either for testing or as browser-less dependency DOM env, basicHTML with linkedom" makes it sound like you have, but just naively scanning the linkedom readme, and search for "jest" in this repo, so far I'm not seeing anything obvious. Or is this just really easy to do and I'm missing it?

Thanks!

**Comment by WebReflection** [comment]
I don't use jest but others are AFAIK using linkedom with jest and, unless you need to evaluate `<script>` or `<style>` in the page, linkedom works pretty much out of the box.

See https://github.com/WebReflection/linkedom/issues/15

**Comment by stephenh** [comment]
Gah! Sorry for missing the closed issue. Thank you!

I need to poke around some more, but so far with like ~10 lines of code from #15, have our test suite running with only a single failure, and the time dropped from ~80 seconds to ~60 seconds, which is a ~20% increase basically for free. Amazing work!

**Comment by WebReflection** [comment]
Thanks for the update, I wish it gave you more, as it usually drops from seconds to milliseconds. If you find any specific bottleneck, please feel free to open a new issue, but if you evaluate DOM scripts a lot, I’m afraid there’s not much else I can do, as that would be your bottleneck

**Comment by stephenh** [comment]
Cool, so I am poking around a bit more; does linkedom support `window.location`? I know that seems like a naive question, but instead of the #15 snippet:

```
// and then ...
class JSDOMEnvironment implements JestEnvironment {
  dom: function JSDOM(html) { return parseHTML(html).defaultView; } | null
// ...
```

But I didn't think the `dom is a function` was quite right, from looking at the current jsdom code, where it looks like just a property.

So I found this happydom alternative jest env:

https://github.com/capricorn86/happy-dom/blob/master/packages/jest-environment/src/index.ts

And have altered it to this:

https://gist.github.com/stephenh/056a500708243e2ea43246c28d19d3ae

However, the jest test fails in here:

```
  if (!foundDevTools && canUseDOM && window.top === window.self) {
    // If we're in Chrome or Firefox, provide a download link if not installed.
    if (navigator.userAgent.indexOf('Chrome') > -1 && navigator.userAgent.indexOf('Edge') === -1 || navigator.userAgent.indexOf('Firefox') > -1) {
      var protocol = window.location.protocol; // Don't warn in exotic cases like chrome-extension://.

      if (/^(https?|file):$/.test(protocol)) {
        // eslint-disable-next-line react-internal/no-production-logging
        console.info('%cDownload the React DevTools ' + 'for a better development experience: ' + 'https://fb.me/react-devtools' + (protocol === 'file:' ? '\nYou might need to use a local HTTP server (instead of file://): ' + 'https://fb.me/react-devtools-faq' : ''), 'font-weight:bold');
      }
    }
  }
```

Where it's trying to call `window.location.protocol`, but `window.location` is undefined.

From setting breakpoints after the `const { window } = parseHTML(...)` line and inspecting the `window` object returned from `parseHTML`, I indeed don't see a `window.location` key.

Am I missing something? Thanks!

**Comment by donferi** [comment]
Hey @stephenh did you manage to figure this out? I'm also struggling setting it up for Jest, mostly because I don't know what I'm doing. It would be awesome if we could get a `jest-environment` package working with `linkedom`.

**Comment by mikemadest** [comment]
I manage to run a simple test but I ran into a few issues (missing `getComputedStyle`, `getRootNode` and `NamedNodeMap`), also onClick events don't seem to work yet.

This was done using @stephenh code as a base as well as spending some time checking jsdom and happy dom codes:
https://github.com/mikemadest/jest-environment-linkedom

Posting this in case this provide any help or generate enough interest to increase working code (I realised this issue is marked as "closed" but unless I miss something there is still much to say or do there).

**Comment by WebReflection** [comment]
I think NamedNodeMap is in, not sure about getRoot functionality, but also not much interest in getComputedStyle, unless cssom helps there. Par welcome
