### ISSUE TITLE
window.perfomance object doesn't exist

### ISSUE THREAD

**Issue by cmolina** [WebReflection/linkedom#51]
Hi! I am using this library to run unit tests over a library I work on. Great work.

I realized the [`window.perfomance` object](https://developer.mozilla.org/en-US/docs/Web/API/Window/performance) is missing. Do you have plans to add it?

If you do, with the right instructions I could volunteer to include it. I read the code and I believe it should live under `interface`.

Best, Carlos

**Comment by WebReflection** [comment]
Exposing `window.performance` via `perf_hooks` NodeJS module, I hope that works :wave:
