### ISSUE TITLE
Missing `range.createContextualFragment(html)`

### ISSUE THREAD

**Issue by Lcfvs** [WebReflection/linkedom#52]
Hi,

Is it possible to add it, please? :P

**Comment by WebReflection** [comment]
How about a PR instead? Or better, I won’t work on this any time soon, but you can contribute 👋

**Comment by Lcfvs** [comment]
I can try to do that during the next days... just some little pushes on my own things before, since it's awaited by some contacts for their projects... but I don't forget it, I promise to try. ;)

**Comment by amb26** [comment]
Cheers - just adding my vote for this feature - not in a huge hurry, just want to register my interest :)

**Comment by Lcfvs** [comment]
@WebReflection Seems ok, please? :)

**Comment by WebReflection** [comment]
@Lcfvs I have [some comment](https://github.com/Lcfvs/linkedom/commit/0e41a7a950db37c156b72a70300a637cef085e68#r50095041) but I don't understand why that's not a PR to this repository 🤔

**Comment by Lcfvs** [comment]
@WebReflection Sorry, I just made it ;)

**Comment by WebReflection** [comment]
It's up and running 👋
