### ISSUE TITLE
Error: :nth-last-child isn't part of CSS3

### ISSUE THREAD

**Issue by t7yang** [WebReflection/linkedom#58]
I got an error:

```
Error: :nth-last-child isn't part of CSS3
    at Object.compilePseudoSelector (...\node_modules\css-select\lib\pseudo-selectors\index.js:29:15)
    at Object.compileGeneralSelector (...\node_modules\css-select\lib\general.js:21:39)
    ...
```

with selector like this

```js
document.querySelectorAll('.t01 > tr:nth-last-child(n+2)')
```

but isn't the `nth-last-child` already supported by [CSS3](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-child#browser_compatibility)?

My environment:

- linkedom: 0.7.6
- node: 15.14.0
- OS: Windows 10 21H1 19043.964

**Comment by fb55** [comment]
This was "solved" in the latest css-select version: This seems to stem from a shortcoming of the `strict` option.

I wasn't aware of anyone using the `strict` option, and removed it in the last major version. @WebReflection Please let me know if this is essential for this module, and we can talk about re-introducing it. Without the option, users will simply be able to use a few more selectors.

**Comment by WebReflection** [comment]
@fb55 thanks for chiming in! My main concern here is: is this [adapter](https://github.com/WebReflection/linkedom/blob/main/esm/shared/matches.js) able to deal with all exotic CSS selectors that non `strict` allows? I think I had issues with non-strict before, hence simplified the adapter to work with selectors I could test and use here .... but if you believe that adapter covers all cases already, I'd be more than happy to enable all CSS things, and drop the `strict` property.

Thank you 👋

**Comment by WebReflection** [comment]
@t7yang @fb55 OK ... I've removed it ... no regression found, I hope latest works well now.
