### ISSUE TITLE
Docs: JSDOM to Linkedom?

### ISSUE THREAD

**Issue by henricook** [WebReflection/linkedom#59]
Hi 👋🏻 ,

Linkedom looks like a great project, i've got a project that spends tens of seconds in JSDOM and I'd love to try Linkedom as a replacement. I sense that's it not a drop in replacement, has anyone written a 'migration guide' - or is a conversion instead of a rewrite far more complex than I think it might be?

**Comment by WebReflection** [comment]
The README contains a JSDOM like bootstrap. If your project uses globals, it’s up to you assign those globals. Does this help?

**Comment by henricook** [comment]
Sorry I'd totally missed that, thanks! I've got a few things now that are not-quite-like-JSDOM yet, is there a chatroom or mailing list I could post them to once I manage to make small recreation cases?

**Comment by WebReflection** [comment]
https://github.com/WebReflection/discussions/discussions

**Comment by henricook** [comment]
Thanks, it's my day for failing at GitHub!

**Comment by henricook** [comment]
@WebReflection you sir, are a legend.

What's was taking 35 seconds in JSDOM takes 11 seconds for Linkedom and results (so far) look identical!
