### ISSUE TITLE
Attributes missing

### ISSUE THREAD

**Issue by cramforce** [WebReflection/linkedom#6]
Hey,

I was porting code like this https://github.com/google/eleventy-high-performance-blog/blob/main/_11ty/apply-csp.js#L54 and this https://github.com/google/eleventy-high-performance-blog/blob/main/_11ty/json-ld.js#L35 and both of those selectors fail. From my debugging it looks like those attributes (`csp-hash` and `type`) on `script` aren't parsed (I logged the outerHTML of the nodes and didn't see the attributes).

Besides that things are working great and the performance is very much appreciated!

Cheers!

**Comment by WebReflection** [comment]
I've just tried:

```js
const {document} = parseHTML('');
document.head.innerHTML = `<script csp-hash="any"></script>`;
console.log(document.querySelectorAll("script[csp-hash]")[0].toString());
```

And the outcome is:
```html
<script csp-hash="any"></script>
```

While `document.toString()` produces:
```html
<!DOCTYPE html><html><head><script csp-hash="any"></script></head></html>
```

Is it something *inside* the script that is not available? `<script>`, together with `<style>` or `<textarea>` and `<title>` have a special behavior for content, as these don't accept *Element* nodes inside.

**Comment by WebReflection** [comment]
P.S. the *window*, in *linkedom*, has to be retrieved via `document.defaultView` *but* it doesn't have a document attached ... *that* is something I can fix thought

**Comment by WebReflection** [comment]
I've made a few changes that *maybe* help you sorting out what's going on:
https://github.com/WebReflection/linkedom#simulating-json-bootstrap

**Comment by WebReflection** [comment]
@cramforce there are a lot of tiny fixes in the latest version, please have a look at both *how to simulate JSOM* and with latest, to see if your problem is gone.

I don't have much to reproduce or test, so if I won't hear from you in a couple of days, I'll close this 👋

**Comment by cramforce** [comment]
The new version doesn't fix it, but I have a minimal repro:

```js
const { parseHTML } = require("linkedom");

console.log(
  `type="test" is retained`,
  parseHTML(`<!doctype html><script type="test"></script>`).document.toString()
);

console.log(
  `type="test" is dropped`,
  parseHTML(`<!doctype html><script type="test">X</script>`).document.toString()
);
```

**Comment by WebReflection** [comment]
Thanks for the reproducible example!

FWIW, it's a specific `<script>` special case (change name to see it working), meaning it likely affects `<style>` and `<title>` too ... these are all special cases, and I'll try to fix this ASAP as these are also most important nodes that should work 😅

thank for your patience, I'll come back hopefully sooner than later.

**Comment by WebReflection** [comment]
@cramforce this issue has been fixed, I hope you won't have any other, but if that's the case, please open a new issue and I'll follow up. Thanks for the example, it helped a lot (and it should've been in my coverage in the first place).

Now all cases are tested, and it's green 👍
