### ISSUE TITLE
Contributor documentation: Running tests, working in IntelliJ

### ISSUE THREAD

**Issue by henricook** [WebReflection/linkedom#60]
Hi @WebReflection ,

The `how-to-contribute.md` suggested creating an issue for further documentation that I think might be useful.

I'm trying to get to grips with the project so I can maybe solve my own problems, let me tell you how I got started and maybe in the process of telling me what I should have done it'll become apparent what to add to the docs.

I want to look at the `toString`'ing of `Element` so I found a test file. I couldn't see any sections e.g. like in Jest (`it("test thing thing")`), I assumed this `assert` format is a stylistic thing but since I'm fixing one very defined problem for now I didn't want to spend time reading about it just yet. I just commented out the whole of `test/html/element.js` and added in one test for my issue at the top whilst I tried some things out:

```javascript
const {document} = parseHTML('<!DOCTYPE html><html id="html" class="live"><!--&lt;hello&gt;-->&lt;hello&gt;</html>');
document.documentElement.innerHTML = '<div>Foo&nbsp;&nbsp;&nbsp;Bar</div>'
assert(document.documentElement.toString(), '<div>Foo&nbsp;&nbsp;&nbsp;Bar</div>')
```

I usually work in IntelliJ, I tried to run the test from there but it can't make sense of the global.symbolFor stuff:

![image](https://user-images.githubusercontent.com/82004/118689983-8290c000-b7ff-11eb-804a-51a653d5e538.png)

So I went to the CLI and luckily `npm run test -- test/html/element.js` - a pretty standard syntax seemed to work. **It would be great to have test commands documented**.

I got a lot of output though, a lot of things that I probably don't need when I'm just iterating on one little test, a big table with these headers: `File                              | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s    `

So **it would be great to know how to not get all this stuff in the output whilst I'm focusing on a small task**. Of course I'd come back and run a full test suite afterwards. I appreciate it's probably important a lot of the time, but it's quite daunting to a newbie.

My test output is present about halfway through the big chunk of output from this command, so I can work with it for now. **It would also be helpful to know how you might add `console.log` type statements whilst debugging**, they don't seem to come out in the test output currently. I'd use the debugger, but IntelliJ has issues as above.

**Comment by WebReflection** [comment]
is [this](https://github.com/WebReflection/linkedom/blob/main/test/assert.js#L1-L15) too complicated?

`assert(expression, expected, message = '')` ... you pass a value, you state your expectations, you optionally pass a message to show in the terminal 🤔

**Comment by henricook** [comment]
Ha sorry that really wasn't the focus of my issue here. I was just describing the steps I'd taken to try and be productive for my very narrow issue. I'm sure it's a very valid and handy test framework. I'm coming to this on a tight timeline and trying to see if I can resolve this kind of thing for my application.

Since writing the issue I've spent some more time with this and now know the big table of results is from `c8` and that I can _almost_ just run `node test/index.js` to get pure test results - although I still need the stuff that seeds the global/Symbol.for. 

In a jest-type test suite I'd be looking to write a new test to try out my assumptions and then run just that test from the command line or IntelliJ, as I've mentioned above in the name of speed I just commented out all the code in an existing test files and copy-pasted my own test on top. I could also have created a new file to work in.

I'll try and raise my own MR for the documentation if you'd prefer, once I spend a bit more time with the code base

**Comment by WebReflection** [comment]
I mean ... you are right, I haven't documented that bit, but I am not sure I am following what are your concerns around it, as it's a 5 LOC simplification, 'cause I usually try to avoid unnecessary dependencies in general ... `console.assert` exist for a reason :-)

**Comment by WebReflection** [comment]
maybe I need to read through your first question ... apologies if not super useful so far

**Comment by henricook** [comment]
Yep I really didn't mean to focus on the testing methodology, I think what I'm asking for here is more of a 'getting started' with:

- Here's how to write a test
- Here's how to run a test (just that test, avoiding all the benchmark and codecov output)
- Maybe: how to output console.log from a method in the codebase when testing (I might have just missed something obvious here)

And then something very specific to me:
- how to debug tests in intellij OR how to use a debugger with this

What IDE/debugger do you use with this, if any?

**Comment by WebReflection** [comment]
> What IDE/debugger do you use with this, if any?

I use Codium and `nodejs --inspect-brk` to debug via [nim](https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj/)

**Comment by WebReflection** [comment]
I don't know if this is what you were after, but I think it's already better than nothing.

https://github.com/WebReflection/linkedom/blob/main/how-to-contribute.md#testing---helpers

Feel free to file a MR to improve that section, if you think anything else is needed, thanks.
