### ISSUE TITLE
Empty attributes should be permitted in output 

### ISSUE THREAD

**Issue by henricook** [WebReflection/linkedom#63]
Several advanced HTML use cases, such as attaching `data-` tags for testing purposes can require empty attribute values to be present, currently empty attributes are entirely removed from the string that Linkedom outputs. Here is a test to illustrate the behaviour:

```javascript
const {document} = parseHTML('<!DOCTYPE html><html id="html" class="live"><!--&lt;hello&gt;-->&lt;hello&gt;</html>');

document.documentElement.innerHTML = '<div data-amend="">Foo</div>'

// Assertion fails currently (desired behaviour)
assert(document.documentElement.toString(), '<div data-amend="">Foo</div>')

// Assertion passes currently
assert(document.documentElement.toString(), '<div>Foo</div>')

document.documentElement.innerHTML = '<div data-amend>Foo</div>'

// Assertion fails currently (desired behaviour)
assert(document.documentElement.toString(), '<div data-amend="">Foo</div>')

// Assertion passes currently
assert(document.documentElement.toString(), '<div>Foo</div>')
```

**Comment by WebReflection** [comment]
fixed as minor 👍

**Comment by minas90** [comment]
@WebReflection hi, the correct behaviour is to return an empty value for any attribute, even if in the original html the value was not present. There is no need keep and maintain the list of boolean attributes.

**Comment by henricook** [comment]
Hmm that's an interesting one. I'm looking for:

- empty attributes from source HTML being carried across to the output
- empty attributes I set in code coming out in the output

**Comment by minas90** [comment]
The current fix is both diverted from the standard and is hard to maintain because it has the hardcoded list of boolean attributes. 
Simply try to open this html in Chrome: `<video src="" controls>`, select the video and do `outerHTML`, the controls attribute will get an empty value which is missing in the original html.
I pushed the proper fix #61 about 2 weeks ago, which matches the proper behaviour. It's ignored for some reason.

**Comment by henricook** [comment]
Yes I see, I don't think this supports the use case I mentioned in the issue description where I want to output empty `data-*` tags

**Comment by WebReflection** [comment]
> I pushed the proper fix #61 about 2 weeks ago, which matches the proper behaviour. It's ignored for some reason.

*some reason* is tests failing

**Comment by WebReflection** [comment]
> Yes I see, I don't think the fix supports the use case I mentioned in the issue description where I want to output empty data-* tags

Every non boolean attribute outputs empty strings. You test case is in and it works like the browser would.

**Comment by henricook** [comment]
> > Yes I see, I don't think the fix supports the use case I mentioned in the issue description where I want to output empty data-* tags
> 
> Every non boolean attribute outputs empty strings. You test case is in and it works like the browser would.

Ah, apologies if I misread

**Comment by WebReflection** [comment]
both cases (video controls) and empty data attributes are tested:
https://github.com/WebReflection/linkedom/blob/main/test/html/element.js#L145-L148

**Comment by minas90** [comment]
Hi @WebReflection,
The second test simply checks the current incorrect behaviour.  :)
Please try to experiment with Chrome's console for example.

Here is the output from console:
```
div.innerHTML = '<video src="" controls>';
"<video src=\"\" controls>"
div.innerHTML
"<video src=\"\" controls=\"\"></video>"
```

So the test actually should be:
```
node.innerHTML = '&lt;video src="" controls&gt;';
assert(node.innerHTML, '&lt;video src="" controls&gt;&lt;/video&gt;');
```

We simply need to remove the list of boolean attributes and return empty value no matter what, even if it originally had no value.

**Comment by henricook** [comment]
If I'm understanding you right Minas wouldn't this massively increase output size? E.g. every tag would have a `class=''` (and several others), even if they were never originally set?

**Comment by WebReflection** [comment]
> The second test simply checks the current incorrect behaviour. :)

The third dotted list of the reame:

> be close to the current DOM standard, but not too close.

I think current behavior is desired, and I don't see *any* advantage in *not* having boolean attributes so, unless you tell me what is it that disturbs you particularly in having a terser output when used to serve pages, I am not sure *incorrect* is the right term, as to me is *better*.

I don't care about reflecting standard 100% here ... not sure I have stressed this enough regarding this project: there's JSDOM for that!

**Comment by minas90** [comment]
@henricook no, new attributes are not added, only the value is added if missing  and is empty even if it's a boolean attribute like `controls`, so `<video controls>` will become `<video controls="">`. It's the standard and it's how all the browsers always worked.

**Comment by WebReflection** [comment]
@henricook correct. Empty id, class, or style, are not part of the output, and that's what I think makes most sense. That's also how SSR optimize unnecessary layout parts, but on top of that, having an empty `id`, `class`, or `style`, means that `hasAttribute(x)` is true, even if the attribute is completely meaningless for the parser. Accordingly, as the initial issue has been fixed, I think we should move forward, as I don't want empty attributes to be carried when these are meaningless, or they empty value.

**Comment by minas90** [comment]
> I think current behavior is desired, and I don't see _any_ advantage in _not_ having boolean attributes so, unless you tell me what is it that disturbs you particularly in having a terser output when used to serve pages, I am not sure _incorrect_ is the right term, as to me is _better_.

I think that the desired behavior is the behavior that is expected, but it's your project, so you know better. :)

By the same logic browsers can have their own standards and protocols, so you should have a different code for each.
I also don't care about reflecting standard 100%, but hardcoding some boolean attributes to divert from standard for no good reason (to save 2 bytes?) which will cause inconsistent behavior depending whatever the boolean attribute is in the list or not.

For example right now my code works both in chrome, jsdom and linkedom after I did the change to return the empty value.

**Comment by WebReflection** [comment]
> For example right now my code works both in chrome, jsdom and linkedom after I did the change to return the empty value.

This is not a library that targets *tests* only, it's a library to create output too: the terser, the better.

Your code should work regardless, unless it checks strictly that `controls=""`, in which case I wonder what are you after, what are you testing, and why you can't use a `RegExp` that checks `/attr(?:="")?/` instead ... but as you didn't provide any concrete advantage in not having booleans attribute and filtered id, class, and style, I'm happy to close this conversation and agree to to disagree.

If you'll ever have an actual bug, or issue, please feel free to file a new one.
