### ISSUE TITLE
node.cloneNode(true) causes corruption of document structure

### ISSUE THREAD

**Issue by amb26** [WebReflection/linkedom#66]
Thanks for your extremely rapid attention and released fix for #65. Unfortunately the fix which has been issued has made the situation worse in some aspects and for the time being I have to return to release 0.8.0.

The following code which was functional under 0.8.0 now no longer returns any result for the query under 0.9.1

````
var linkedom = require("linkedom");
var text = "<!DOCTYPE html>\n<html lang=\"en\"><body><div class=\"test-component-include\"></div></body></html>"
var root = linkedom.parseHTML(text).document.cloneNode(true);
var queried = root.querySelectorAll(".test-component-include");
console.log("queried " + queried.length + " elements");
````

In addition part of the original problem reported under #65 is still present in that the classList member of the div node in the cloned markup is not populated. And className neither, which is probably what is responsible for the query failure.

**Comment by WebReflection** [comment]
Yeah, classList needs to add entries, if available, on setup ... sorry for the mess, I hope now it works as expected.

**Comment by WebReflection** [comment]
P.S. your test case now returns 1 element
