### ISSUE TITLE
Missing some dataset features?

### ISSUE THREAD

**Issue by nhoizey** [WebReflection/linkedom#69]
Hi Andrea,

I'm trying to [migrate images-responsiver from basicHTML to LinkeDOM](https://github.com/nhoizey/images-responsiver/issues/138), and it's really working well overall, but I'm having an issue with `dataset` usage.

Here's a reduced test case to understand what I thought would work, but doesn't:

```javascript
const { parseHTML } = require('linkedom');
const { document } = parseHTML(`<!DOCTYPE html>
<html>
<body>
  <img src="test.png" data-responsiver="transform" />
</body>
</html>`);

document.querySelectorAll('img').forEach((image) => {
  console.log('responsiver' in image.dataset);
  console.dir(Object.keys(image.dataset));
  console.log(image.dataset.responsiver);
  delete image.dataset.responsiver;
  console.log(image.dataset.responsiver);
  console.dir(Object.keys(image.dataset));
});
```

Here's the result on my computer (macOS Big Sur v11.4 with Node.js v16.0.0):

```bash
false
[]
transform
null
[]
```

What I would expect:

```bash
true
['responsiver']
transform
undefined
[]
```

Did I forget to use something to better support `dataset`, or is it a missing part in LinkeDOM?

Thanks a lot for your help.

**Comment by WebReflection** [comment]
You read the right value, and dataset is in … but maybe the proxy is not fully instrumented?

**Comment by nhoizey** [comment]
Do you mean I should use `defaultView` as presented in https://github.com/WebReflection/linkedom#simulating-jsdom-bootstrap ?

I'm sorry, I'm not sure I understand what `proxy` means here.

**Comment by WebReflection** [comment]
https://github.com/WebReflection/linkedom/blob/main/esm/dom/string-map.js

The Proxy handler doesn’t implement hasKey and others … MR welcome or I’ll try to add methods later this week

**Comment by nhoizey** [comment]
I'm really sorry, I don't even understand much of the code you shared, I'm more a JavaScript user than a JavaScript developer… 😔

But anyway, there's no urge on my side, no worries. 🙏

**Comment by WebReflection** [comment]
Basically I forgot to initialize the dataset with known data attributes on creation.
Your expectations there should now be met 👋

**Comment by nhoizey** [comment]
It now works as I expected, indeed, thanks a lot! 🙏
