### ISSUE TITLE
LinkeDOM seems to be dealing differently with different HTML entitites

### ISSUE THREAD

**Issue by nhoizey** [WebReflection/linkedom#71]
This is **not an issue for my usage as far as I know**, so feel **free to close the issue** if this is not something useful to "fix".

I'm using v0.9.6 on macOS Big Sur v11.4 with Node.js v16.0.0

When I run this code:

```javascript
const { parseHTML } = require('linkedom');
const { document } = parseHTML(`<!DOCTYPE html>
<html>
<body>
  <p>&lt;img src=&quot;…&quot; /&gt;</p>
</body>
</html>`);
console.log(document.toString());
```

I get this result:

```html
<!DOCTYPE html>
<html>
<body>
  <p>&lt;img src="…" /&gt;</p>
</body>
</html>
```

The `&lt;` and `&gt;` are preserved, but not the `&quot;`.

**Comment by WebReflection** [comment]
The outcome is the same though, visually, and practically speaking, right?

there’s some escaping shenanigan due the HTML parser, and the safety guards In linkedom, so that no XSS happens, but some char gets normalized.

As security is preserved, is this affecting real world use cases?

**Comment by nhoizey** [comment]
I agree there will probably be no issue in HTML.

I was wondering how it would impact inline JavaScript for example, so I wrote that:

```javascript
const { parseHTML } = require('linkedom');
const { document } = parseHTML(`<!DOCTYPE html>
<html>
<body>
<script>
let foo="&quot;bar&quot;";
console.log(foo);
</script>
</body>
</html>`);
console.log(document.toString());
```

The `&quot;` are preserved:

```html
<!DOCTYPE html>
<html>
<body>
<script>
let foo="&quot;bar&quot;";
console.log(foo);
</script>
</body>
</html>
```

So I guess it's sage to keep is as it is.

**Comment by WebReflection** [comment]
AFAIK both JS and CSS should work without issues, and so textarea, title, and all others that accepts only text ... thanks for double-checking though 👍

**Comment by nhoizey** [comment]
Great! You're welcome.

**Comment by monochromer** [comment]
I have a similar issue.

Fox example, after process and serialization this snippet:
```html
<!DOCTYPE html>
<title>Article about &lt;style&gt; tag</title>
```
i get the following
```html
<!DOCTYPE html>
<title>Article about <style> tag</title>
```
Browsers works fine with this html, but some tools, like _html-minifier_, break down.

Full code for test:
```javascript
const fs = require('fs');
const { parseHTML } = require('linkedom');
const { minify } = require('html-minifier');

const fileContent = fs.readFileSync('./index.html', { encoding: 'utf-8' });
const DOM = parseHTML(fileContent);
const content = DOM.document.toString()
console.log(content)

const minContent = minify(content, {
  removeComments: true,
  collapseWhitespace: true,
})
console.log(minContent);
```

**Comment by WebReflection** [comment]
> Browsers works fine with this html

it's not that they work fine, the title can have anything in it ... 

now, try this:

```js
document.title = 'Article about &lt;style&gt; tag'
```

what do you read? the `Article about <style> tag` you seem to expect, or the escaped sequence?

Here we have what *you* in the first place would expect!

> but some tools, like html-minifier, break down.

then I suggest you file a bug in there?
