### ISSUE TITLE
StyleSheet implementation

### ISSUE THREAD

**Issue by Kal-Aster** [WebReflection/linkedom#73]
Hi, thanks for this library.

Is [StyleSheet](https://developer.mozilla.org/en-US/docs/Web/API/StyleSheet) (`HTMLStyleElement.sheet` property) available?
It always returns me `undefined` and I can't find the implementation in the source code.

**Comment by WebReflection** [comment]
<iframe src="https://giphy.com/embed/in6mnJNYjGKpq" width="480" height="320" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/reaction-in6mnJNYjGKpq">via GIPHY</a></p>

that's a big one ... no time (nor needs) here, but MR welcome 👋

**Comment by WebReflection** [comment]
**actually** ... there is a module for that: https://github.com/NV/CSSOM/blob/master/lib/index.js

*maybe* I could `import` that and add it as setter? not sure how it'll work though, but I am not planning to re-write that part.

**Comment by Kal-Aster** [comment]
I think I can help doing it. I just need some time to wrap my head around the source code, it's quite different from how I use to program.

If you could point me where this patch should go, more or less, that would be a great start!

**Comment by WebReflection** [comment]
this is how I'd go:

```js
import {CSSStyleSheet} from 'cssom';

import {registerHTMLClass} from '../shared/register-html-class.js';

import {TextElement} from './text-element.js';

const tagName = 'style';

/**
 * @implements globalThis.HTMLStyleElement
 */
class HTMLStyleElement extends TextElement {
  constructor(ownerDocument, localName = tagName) {
    super(ownerDocument, localName);
  }
  get sheet() {
    return new CSSStyleSheet();
  }
}

registerHTMLClass(tagName, HTMLStyleElement);

export {HTMLStyleElement};
```

**Comment by Kal-Aster** [comment]
Ok, thanks

However it is not problematic, it's just a project structure different from those of mine, so I have to explore a bit to orient myself. I read the "how to contribute" and I think it's explains the project well enough

**Comment by Kal-Aster** [comment]
I just clone the repo and run `npm test` and it gives me
```cmd
> linkedom@0.9.7 test
> eslint esm/ && npm run hello && node test/benchmark/linkedom.js --w3c --mutation-observer --custom-elements && c8 node test/index.js && c8 report -r html       

(node:1992) [ESLINT_PERSONAL_CONFIG_SUPPRESS] DeprecationWarning: '~/.eslintrc.*' config files have been deprecated. Please remove it or add 'root:true' to the config files in your projects in order to avoid loading '~/.eslintrc.*' accidentally. (found in "..\..\..\..\..\.eslintrc")
(Use `node --trace-deprecation ...` to show where the warning was created)       

> linkedom@0.9.7 hello
> if [[ "$(node --version)" =~ ^v1[^2] ]]; then node --input-type=module -e "import {DOMParser} from './esm/index.js';console.log('\x1b[7m\x1b[1m',(new DOMParser).parseFromString('<html>LinkeDOM<canvas /></html>','text/html').querySelectorAll('html')[0].firstChild.toString(),'\x1b[0m')"; fi

"$(node --version)" non atteso.
```
Am I doing something wrong?
I'm on Windows, is it for this?

**Comment by WebReflection** [comment]
In Windows ... ed in Italiano ... 😁 ... I suggest WSL or to comment out with a `#` prefix that line while testing. I hope the rest works as expected, but yeah, Linux or Mac are usually what I can test/where I test development stuff, sorry.
