### ISSUE TITLE
querySelector with :scope failing unexpectedly

### ISSUE THREAD

**Issue by pkra** [WebReflection/linkedom#75]
Re-using the example from the readme, the following minimal example failed unexpectedly:

```js
const {parseHTML} = require ('linkedom');

const {
 document
  } = parseHTML(`
    <!doctype html>
    <html lang="en">
      <head>
        <title>Hello SSR</title>
      </head>
      <body>
        <form>
          <input name="user">
          <button>
            Submit
          </button>
        </form>
      </body>
    </html>
  `);


const form = document.querySelector('form');
const button = form.querySelector(':scope > button');
console.log(button); // returns null while DOM would return the button
```

I realize that this might be a bug in `css-select` but I don't know it well enough to figure things out.

**Comment by WebReflection** [comment]
Where is the error message?

**Comment by pkra** [comment]
> Where is the error message?

There's no error message as such - `form.querySelector(':scope > button');` returns `null` instead of the node representing the button.

**Comment by WebReflection** [comment]
I see ... then [they say it's supported](https://github.com/fb55/css-select/issues/343), but it returns `null` here ... I don't do anything too special with that module, I just [provide callbacks](https://github.com/WebReflection/linkedom/blob/main/esm/shared/matches.js) as mentioned in their documentation, and I don't have actual time to dig into a possible 3rd party module these days ... could you please try to figure out why would that fail? Thanks!

**Comment by pkra** [comment]
Trying to take a closer look, it seems to come down to prepareMatch from parent-node.js, so if it's not  the adapters, then it's probably CSSselect.

**Comment by pkra** [comment]
Ah, cross-post. Yes, I'll try to take a look at css-select.

**Comment by blake-regalia** [comment]
Any progress on this?

**Comment by blake-regalia** [comment]
I believe this can be supported with `context` and `relativeSelector` options:
https://github.com/fb55/css-select/issues/709#issuecomment-1111339997

**Comment by pkra** [comment]
Thank you @blake-regalia for tracking this down and proposing a fix!

**Comment by WebReflection** [comment]
[fix landed](https://github.com/WebReflection/linkedom/commit/1ec427dc66cb68e62ad4626fad8f9ba926487152) and this use case works as expected
