### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by matthewp** [WebReflection/linkedom#79]
Hello, I noticed that there is the `rollup/es.config.js` which (I think?) is unused. So I modified it and built an ESM bundle of this library and published it as a fork which you can see here: https://unpkg.com/@matthewp/linkedom@0.10.0/es.js. This works in Deno.

First, are you interested in a build that works with Deno? If not that's fine, I can maintain my fork. Otherwise I'd be happy to contribute here.

My experiment is missing a few things:

* The canvas CJS stuff didn't bundle. I didn't look into why, I just removed it. Could possibly be fixed.
* I removed the perf_hooks import, but I think that can be polyfilled in a bundle.
* I didn't attempt to run any tests in Deno so how *much* works is still an unknown 😀, but a smoke test works so I'm happy.

**Comment by WebReflection** [comment]
I think that came up automatically via [modulestrap](https://github.com/WebReflection/modulestrap#readme), but indeed it's not used anywhere in here, although that *might* be used to have LinkeDOM in ServiceWorker or Web Workers, in general, where no DOM is available. In those cases, the canvas CJS stuff is not needed, and it's likely not going to work anyway, and so goes for the perf_hooks, so your contribution is more than welcome, and if it could produce something consumable on the client side too, it'd be **awesome**!

**Comment by matthewp** [comment]
Ok great, I don't see why it wouldn't work in a worker environment (web/service workers, cloudflare workers, etc).  I think I can write a inline rollup plugin to replace perf_hooks with globalThis.performance since that's in all of the environments aside from Node, and I think the plugin can also replace the canvas impl with an empty object or something, that way the src code doesn't need to be modified at all.

**Comment by WebReflection** [comment]
Yup, that’s how I’d go too, I use a rollup plugin called rollup-plugin-includepaths that replaces imports with whatever you want, and those two imports can be what you described 👍
