### ISSUE TITLE
Invalid handling of uppercased elements in query selector

### ISSUE THREAD

**Issue by WilcoKruijer** [WebReflection/linkedom#81]
Thanks for the great library! I have ran into the following issue.

(I'm using Deno v1.11.5, but I think that shouldn't matter.)

This snippet produces the following result using your library:
```typescript
import {
  DOMParser,
} from "https://cdn.skypack.dev/linkedom@v0.11.0/worker.js?dts";

const documentString = `
<Something>
  <Element>Text</Element>
  <Element>Text</Element>
</Something>`

const d = new DOMParser().parseFromString(documentString, "text/xml");

const nodeListUpper = d.querySelectorAll("Element");
const nodeListLower = d.querySelectorAll("element");

console.log(nodeListUpper.length, nodeListLower.length);
```
Output: `0 2`. (I.e. it only finds the elements with the lowercased query selector)

Running the same snippet (without the import statement) on Chrome results in Output: `2 0`, it only finds the uppercased element.

I believe your library should produce the same result, as the document string actually uses uppercase tags.

Thanks again!

**Comment by WebReflection** [comment]
If you care about case sensitive names you should parse as text/xml

**Comment by WebReflection** [comment]
oh, I've missed that! definitively a bug then 👍
