### ISSUE TITLE
Can't get src of iframe via `src` property

### ISSUE THREAD

**Issue by monochromer** [WebReflection/linkedom#82]
`iframe.src` return `undefined`,  but `getAttribute('src')` return a desired link

**Comment by WebReflection** [comment]
Yup, [nothing like that in the class](https://github.com/WebReflection/linkedom/blob/main/esm/html/i-frame-element.js).

[PR welcome](https://github.com/WebReflection/linkedom/blob/main/how-to-contribute.md#htmlclasses-contributions) 👋

**Comment by artalar** [comment]
@WebReflection thanks for your work on the linkedom!
I am a little confused by this issue, which I found after reproducing my [own problem (the `src` property of script element is empty)](https://stackblitz.com/edit/linkedom-script-src-messing). Why is it is not a bug and what is the reason for that? In normal elements in a real document `src` properties are available.

**Comment by WebReflection** [comment]
It's open, and it could be a bug, for what it matters, I just didn't have the time ... PR welcome.

**Comment by RishiKumarRay** [comment]
@WebReflection in which file do we have to make the changes?

**Comment by WebReflection** [comment]
@RishiKumarRay this class should have that getter https://github.com/WebReflection/linkedom/blob/main/esm/html/i-frame-element.js

hints here around contribution for HTML classes https://github.com/WebReflection/linkedom/blob/main/how-to-contribute.md#htmlclasses-contributions

**Comment by WebReflection** [comment]
@monochromer , @artalar , @RishiKumarRay [this change](https://github.com/WebReflection/linkedom/commit/619bf5dc873b70e6f0897681b549fcb45a515c19#diff-23262225a70fe4471f0ae8fdb944e208e37ab8a111440a77fb2ddf4496149bd0) is all it took to have the `.src` accessor, please use this MR as reference in case you'd like to have other components/elements/accessors exposed out there 👋
