### ISSUE TITLE
Ability to pass options to `htmlparser2`

### ISSUE THREAD

**Issue by lamplightdev** [WebReflection/linkedom#94]
Hi! Great project :)

I was wondering what you thought about adding the ability to pass options somehow to `htmlparser2`?

My use case is server rendering Web Components with the following syntax to set property values:

`<my-element .name="${name}"></my-element>`

which works great, but when parsing the following:

`<my-element .firstName="${name}"></my-element>`

the attribute name (`.firstName`) is lowercased which makes it impossible to parse and set the property as `firstName` - instead it gets set as `firstname`.

`htmlparser2` has the option `lowerCaseAttributeNames` which defaults to `true` but can be set to `false` which would overcome this problem.

As this is not "standard" behaviour I can see why you might be against adding a similar option, or the ability to pass through options, but thought I'd get your opinion?

Thanks!

**Comment by WebReflection** [comment]
I actually never want `lowerCaseAttributeNames` to be true, as [uhtml](https://github.com/WebReflection/uhtml#readme) works the same, and [uhtml-ssr](https://github.com/WebReflection/uhtml-ssr#readme) would suffer this as well, among [ube](https://github.com/WebReflection/ube#readme) or [ube-ssr](https://github.com/WebReflection/ube-ssr#readme) and all others similar projects. Thanks for the heads-up 👍

**Comment by WebReflection** [comment]
Done, no attributes changed whatsoever! I'll consider options once all sane defaults are in, as those options collide a bit with the standard API, so I wouldn't know where to offer those. I hope this makes sense.

**Comment by lamplightdev** [comment]
Fantastic, perfect, thanks :)

**Comment by lamplightdev** [comment]
I'm actually using the `worker.js` output, and it doesn't look like this gets built as part of the release - is that intentional?

**Comment by WebReflection** [comment]
@lamplightdev 

> is that intentional?

nope, just realized worker build is not part of the build ... now it's up, but there are circular dependencies around cssom, yet that's not really linkedom thing, I hope it works, please let me know if it doesn't
