### ISSUE TITLE
HTML encoding rules corrupt contents of comments during round-tripping

### ISSUE THREAD

**Issue by amb26** [WebReflection/linkedom#97]
Small early Christmas present - 

The parser's behaviour on comments produces an extra level of HTML encoding for the basic entity characters (<, >, ") which corrupts their contents during the round-tripping process.
The following code
````
var linkedom = require("linkedom");
var text = "<html><body><!-- This is a comment relating to a <div> tag --></body></html>"
var root = linkedom.parseHTML(text);
var outText = root.document.documentElement.outerHTML;
console.log("Round-tripped markup: " + outText);
````
rather than reproducing the original document, instead outputs 
````
Round-tripped markup: <html><body><!-- This is a comment relating to a &lt;div&gt; tag --></body></html>
````

Unfortunately since linkedom's API does not seem to allow access to any representation of the comment text that does not receive a further round of entity encoding, it seems essentially impossible to represent the input document text above using its nodes.

I guess but have not checked that the same issue affects parsing of CDATA sections.

**Comment by WebReflection** [comment]
So ... basically `toString()` for comments should never escape a thing, right? it might be very simple to fix if that's the case.

**Comment by WebReflection** [comment]
wrote bad commit message but https://github.com/WebReflection/linkedom/commit/51904113937e5f16ab2a5415036ac39bf6bb1428 fixed this issue.

**Comment by amb26** [comment]
Awesome, thanks so much - this'll let me ditch an unsightly batch of workaround code :)
