### ISSUE TITLE
Incorrect types for some `Node` methods

### ISSUE THREAD

**Issue by gingerchris** [WebReflection/linkedom#99]
I'm using linkedom in a typescript project and experiencing some inaccurate typescript errors when using methods like `removeChild` from an instance of `Node`.  The functionality is working as expected, which leads me to believe the error is incorrect.

The error presented is `Expected 0 arguments, but got 1.` which I believe stems from the [declared type for this method here](https://github.com/WebReflection/linkedom/blob/main/types/interface/node.d.ts#L44)

I've put together a minimal reproduction of the issue [here](https://codesandbox.io/s/linkedom-removechild-typescript-error-odmhe)

Also here's a screenshot showing the error:
![Screenshot 2022-01-20 at 12 13 32](https://user-images.githubusercontent.com/1153616/150343361-11b8b34c-4f0a-4819-ac64-09b15e3898d4.png)

Thanks for your work on this project, it's amazing.

**Comment by WebReflection** [comment]
@gingerchris thanks for filing this issue but I am not really a TS and everything TS related is usually provided by the community, so any PR would be more than welcome and yes, definitively I see something ain't right there, and probably there are other methods too not fully aligned ... do you mind proposing those changes? Thank you!

**Comment by gingerchris** [comment]
@WebReflection absolutely, I'll pull a PR together.

**Comment by WebReflection** [comment]
This was closed by https://github.com/WebReflection/linkedom/pull/100
